Polish translation: W3C Accessibility Standards Overview
w3c/wai-website pull request #531
Opened 2024-06-26 22:41 UTC by zwiastunsw

Fix https://github.com/w3c/wai-translations/issues/246

I added index.pl.md file

2024-07-15 23:53 UTC, zwiastunsw commented on pages/standards-guidelines/index.pl.md
> +Konsorcjum World Wide Web (W3C) opracowuje międzynarodowe standardy internetowe: <abbr title="Język Znaczników Hipertekstu">HTML</abbr>, <abbr title="Kaskadowe arkusze stylów">CSS</abbr> i wiele inny
Yes

2024-07-16 00:05 UTC, zwiastunsw commented
@viking-pl: Thanks for reviewing. I have incorporated almost all the suggestions, except:
- "Wytyczne dotyczące dostępności" - we use "Wytyczne dla dostępności...", according to the official WCAG translation in Polish,
- "narzędzia autorskie" - even if it is a neologism in Polish, it is created according to an existing pattern (e.g. "narzędzia ślusarskie", "narzędzia malarskie"), more convenient to use than the descriptive "narzędzia do tworzenia treści (internetowych)"; the term is already used in other translations

2024-08-12 09:33 UTC, remibetin commented
Hi @viking-pl,

Would you have some time to take another look at @zwiastunsw's translation and comments?

Thanks much for your greatly appreciated help.

2024-08-28 16:10 UTC, jcabak requested changes

2024-08-28 16:10 UTC, jcabak commented on pages/standards-guidelines/index.pl.md
> +Ta strona jest wprowadzeniem do wytycznich i innych standardów dotyczących dostępności stron internetowych.
wytycznych

2024-08-28 16:10 UTC, jcabak commented on pages/standards-guidelines/index.pl.md
> +### Wytyczne dla dostępności narzędzii do tworzenia treści (ATAG) {#atag}
narzędzi

2024-08-28 16:10 UTC, jcabak commented on pages/standards-guidelines/index.pl.md
> +- [[Omówinie WCAG-EM: Metodologia oceny zgodności dostępności strony internetowej]](/test-evaluate/conformance/wcag-em/) &mdash; WCAG-EM to metoda określania, jak dobrze strona internetowa jest zgodn
Omówienie

2024-08-28 16:10 UTC, jcabak commented on pages/standards-guidelines/index.pl.md
> +[[Omówienie WAI-Adapt]](/adapt/) &mdash; WAI-Adapt umożliwia użytkownikom dostosowywanie (lub „personalizowanie”) sposobu prezentowania treści do swoich potrzb i preferencji. Twórcy treści mogą korzy
potrzeb

2024-08-29 13:03 UTC, remibetin commented
Hi @jcabak,

Thanks for adding suggestions for @zwiastunsw's consideration. We always welcome new contributions and I noticed your interest in previous translations!

According to our [policy](https://www.w3.org/WAI/about/translating/reviewing/#volunteer), would you please send an email to [group-wai-translations@w3.org](mailto:group-wai-translations@w3.org) to introduce yourself and your interest in joining the WAI translator volunteers community?

I look forward to guiding you through the next steps.

2024-11-18 15:03 UTC, remibetin commented
Hi @zwiastunsw,

I have not heard from @jcabak. Are there any suggestions you would like to include in the translation?

2024-11-18 15:04 UTC, remibetin commented
@viking-pl Do you have additional comments on your side?

2024-12-05 09:45 UTC, jcabak commented
> I have not heard from @jcabak. Are there any suggestions you would like to include in the translation?

Hey, the day after you asked me, I sent you an email to group-wai-translations@w3.org - did you get it? I haven't received any response

2024-12-05 09:46 UTC, jcabak commented
> I have not heard from @jcabak. Are there any suggestions you would like to include in the translation?
Hey @remibetin , the day after you asked me, I sent you an email to group-wai-translations@w3.org - did you get it? I haven't received any response

2024-12-10 22:31 UTC, remibetin commented
> Hey @remibetin , the day after you asked me, I sent you an email to [group-wai-translations@w3.org](mailto:group-wai-translations@w3.org) - did you get it? I haven't received any response

@jcabak Unfortunately no. To prevent forgeries and spam, you may have received an automatic e-mail asking you to confirm that you are the sender of the message. Could you please check if you have received such an e-mail, or try sending your e-mail again?

2024-12-10 22:41 UTC, jcabak commented
> > Hey @remibetin , the day after you asked me, I sent you an email to [group-wai-translations@w3.org](mailto:group-wai-translations@w3.org) - did you get it? I haven't received any response
> 
> @jcabak Unfortunately no. To prevent forgeries and spam, you may have received an automatic e-mail asking you to confirm that you are the sender of the message. Could you please check if you have received such an e-mail, or try sending your e-mail again?

Sure, I just sent it and confirmed it.

2025-02-17 17:05 UTC, remibetin commented
@jcabak Have you had the chance to see my December 16 email?

2025-05-05 09:43 UTC, merged