Polish translation for Evaluation Tools Overview
w3c/wai-website pull request #569
Opened 2024-06-27 16:50 UTC by zwiastunsw

Fix https://github.com/w3c/wai-translations/issues/193
Added file pages/test-evaluate/evaluation-tools/index.pl.md

2024-07-03 10:34 UTC, viking-pl requested changes
I will review the transcript translation separately.

2024-07-03 10:34 UTC, viking-pl commented on pages/test-evaluate/evaluation-tools/index.pl.md
> +Filmy zawierają podstawową animację ilustrującą to, co mówi głos spoza ekranu. Ludzie są reprezentowani przez postacie ikon.
```suggestion
Filmy zawierają podstawową animację ilustrującą to, co mówi głos spoza ekranu. Ludzie są przedstawieni za pomocą symboli graficznych.
```
NOTES ON OIGINAL TEXT:
There's one video.
I have watched it and the second sentence does not make sense to me (People are represented by icon figures). If that sentence is necessary at all, it should read: "Concepts and ideas are represented by graphical symbols", or something similar.

Hence the text in Polish should rather be:
```suggestion
Film zawiera podstawową animację ilustrującą to, co mówi głos spoza ekranu. Pojęcia i idee są przedstawione w formie symboli graficznych.
```

2024-07-03 10:34 UTC, viking-pl commented on pages/test-evaluate/evaluation-tools/index.pl.md
> +    <td>Narzędzia oceny dostępności cyfrowej</td>
```suggestion
    <td>Narzędzia diagnozujące dostępność cyfrową</td>
```

2024-07-03 10:34 UTC, viking-pl commented on pages/test-evaluate/evaluation-tools/index.pl.md
> +    <td>Narzędzia oceny dostępności cyfrowej</td>
```suggestion
    <td>Narzędzia diagnozujące dostępność cyfrową</td>
```

2024-07-03 10:34 UTC, viking-pl commented on pages/test-evaluate/evaluation-tools/index.pl.md
> +  <p><a href="#alternatives">Omówienie alternatywnych narzędzi oceny - film</a></p>
```suggestion
  <p><a href="#alternatives">„Omówienie narzędzi diagnostycznych” – film</a></p>
```
lub
```suggestion
  <p><a href="#alternatives">Omówienie narzędzi diagnostycznych – film</a></p>
```

2024-07-03 10:34 UTC, viking-pl commented on pages/test-evaluate/evaluation-tools/index.pl.md
> +  <p>Uwaga dotycząca opisu wideo: Wideo na tej stronie nie zawiera zsynchronizowanej audiodeskrypcji, ponieważ obrazy jedynie ilustrują dźwięk i nie dostarczają dodatkowych informacji. W tym przypadk
```suggestion
  <p>Uwaga dotycząca opisu wideo: Wideo na tej stronie nie zawiera zsynchronizowanej audiodeskrypcji, ponieważ obrazy jedynie ilustrują dźwięk i nie dostarczają dodatkowych informacji. W tym przypadku audiodeskrypcja byłaby bardziej rozpraszająca niż przydatna dla większości osób, w tym osób, które nie widzą elementów wizualnych. Opis informacji wizualnych jest zintegrowany w transkrypcji z opisem wizualnym („transkrypcja opisowa”).</p>
```

2024-07-03 14:10 UTC, viking-pl requested changes
review of the video transcript part

2024-07-03 17:07 UTC, zwiastunsw commented
@viking-pl Dziękuję za - jak zwykle - solidny przegląd. Uwzględniłem prawie wszystkie poprawki z wyjątkiem dwóch, o których poniżej. 
1. Propozycja tłumaczenia "evaluation tools" na "narzędzia diagnostyczne" (""diagnozujące") jest interesująca, ale w dotychczasowej praktyce tłumaczeń stosowane jest tłumaczenie "narzędzia oceny".
2. Dywitze w "C-M-S" są umieszczone umyślnie, dla czytnika ekranu, tak jak w oryginale.

Ponadto pozostanie jeszcze do uzgodnienia tłumaczenie podpisu pod filmem i nagłówka "Alternatives for Evaluation Tools Overview Video" .

Zaproponowane poprawki w transkrypcji zostały już przeniesione do transkrypcji w "Wybór narzędzi oceny dostępności"

2024-07-04 11:22 UTC, zwiastunsw commented
@remibetin: Could you please run a deploy, so that the work can be completed?

2024-07-15 15:17 UTC, viking-pl approved these changes
I don't like the way "evaluation tools" are being translated, but I get the consistency argument. So I am approving.
Perhaps best to go through all occurances once again and check them for consistency. (narzędzia oceny, narzędzia do oceniania, etc.)

2024-07-15 17:41 UTC, zwiastunsw commented on pages/test-evaluate/evaluation-tools/index.pl.md
> +[[Wybór narzędzi oceny dostępności cyfrowej]](/test-evaluate/tools/selecting/)
Związek "narzędzia oceny" (narzędzia służące do oceny) jest w języku polskim poprawnym związkiem  wyrazowym, podobnie, jak "narzędzia pracy" czy "narzędzia zbrodni" obok równie poprawnego i częstego wg wzorca "narzędzia...[jakie?]... chirurgiczne, ślusarskie, badawcze, oceniające. Z perspektywy prostego języka oznajmienie złożone z pięciu rzeczowników jest rzeczywiście problematyczne, więc użycie w tym przypadku równoznacznego "narzędzi oceniających" jest uzasadnioną i satysfakcjonującą alternatywą. Akceptuję :)

2024-08-08 10:01 UTC, remibetin commented
@zwiastunsw Please note that the preview is currently broken. To fix this, please rebase this branch against `master`.

2024-08-08 13:18 UTC, remibetin commented on pages/test-evaluate/evaluation-tools/index.pl.md
> +_Ten film jest również dostępny na serwerze W3C: Film: Omówienie narzędzi oceny (format pliku: MP4, rozmiar pliku: 51MB MB)](https://media.w3.org/wai/evaluation-intros/tools-for-evaluating.mp4)._
@zwiastunsw This link is not correctly displayed. A square bracket is missing.

2024-08-08 13:21 UTC, remibetin commented on pages/test-evaluate/evaluation-tools/index.pl.md
> +    <td>Otwiera się skrzynka narzędziowa przy komputerze. Ze skrzynki wychodzi lupa, aby sprawdzić stronę internetową na komputerze. Lupa powiększa słowo „dostępność”.</td>
@zwiastunsw The description seems to have been reworded. Similar to https://github.com/w3c/wai-website/pull/561#discussion_r1679352606

2024-08-08 13:23 UTC, remibetin commented on pages/test-evaluate/evaluation-tools/index.pl.md
> +    <td>Strona w witrynie internetowej jest skanowana. Nad elementami strony pojawia się kolejno znak błędu, powodzenia i znak zapytania.</td>
@zwiastunsw This description seems to have been reworded. Similar to https://github.com/w3c/wai-website/pull/561#discussion_r1679355627

2024-08-08 13:25 UTC, remibetin commented on pages/test-evaluate/evaluation-tools/index.pl.md
> +    <td>Ikona narzędzi jest otoczona czterema ikonami: długopisu, kodu, pędzla i osoby z kluczem.</td>
@zwiastunsw This description seems to have been reworded: the number of icons is not specified in the English version.

Similar to https://github.com/w3c/wai-website/pull/561#discussion_r1679356722

2024-08-08 13:27 UTC, remibetin commented on pages/test-evaluate/evaluation-tools/index.pl.md
> +    <td>Lupa powiększająca znak ostrzegawczy z wykrzyknikiem. Wyświetlanych jest wiele lup. </td>
@zwiastunsw This description seems to have been reworded. Similar to https://github.com/w3c/wai-website/pull/561#discussion_r1679357937

2024-08-08 13:27 UTC, remibetin commented on pages/test-evaluate/evaluation-tools/index.pl.md
> +    <td>Na ekranie 12 pól, w każdym z nich inna osoba przed komputerem.</td>
@zwiastunsw This description seems to have been reworded. Similar to https://github.com/w3c/wai-website/pull/561#discussion_r1679358736

2024-08-08 13:28 UTC, remibetin commented on pages/test-evaluate/evaluation-tools/index.pl.md
> +    <td>Lista dokumentów z rozwijanym polem wyboru i ikoną filtra, pozostają tylko dwa dokumenty.</td>
@zwiastunsw This description seems to have been reworded. Similar to https://github.com/w3c/wai-website/pull/561#discussion_r1679360041

2024-08-08 13:31 UTC, remibetin commented on pages/test-evaluate/evaluation-tools/index.pl.md
> +    <td>Z narzędziami i wiedzą, jak z nich prawidłowo korzystać, masz wszystko, czego potrzebujesz, aby skuteczniej znajdować problemy z dostępnością.</td>
This description seems to have been reworded. Similar to https://github.com/w3c/wai-website/pull/561#discussion_r1679360751

2024-08-08 13:33 UTC, remibetin requested changes
@zwiastunsw I have now reviewed your translation and added some comments. Most issues are similar to those in https://github.com/w3c/wai-website/pull/561.

Let me know what you think!

2024-08-08 13:37 UTC, remibetin commented on pages/test-evaluate/evaluation-tools/index.pl.md
> +    <td>Aby uzyskać więcej informacji o narzędziach oceny dostępności, odwiedź stronę <a href="https://www.w3.org/WAI/evaluation">w3.org/WAI/evaluation</a>.</td>
@zwiastunsw The original version does not contain a link. Please also keep the hyphens (w3.o-r-g/W-A-I/evaluation).

2024-08-12 08:56 UTC, remibetin approved these changes

2024-08-12 09:13 UTC, merged