Include ACT Rules Format 1.1 First Public Working Draft
w3c/wai-website pull request #572
Opened 2024-06-28 13:40 UTC by daniel-montalvo

2024-07-01 11:32 UTC, remibetin requested changes

2024-07-01 11:32 UTC, remibetin commented on pages/about/groups/task-forces/conformance-testing.md
> +- First Public Working Draft: [https://www.w3.org/TR/act-rules-format-1.1/](https:/www.w3.org/TR/act-rules-format-1.1/)
```suggestion
- First Public Working Draft: [https://www.w3.org/TR/act-rules-format-1.1/](https://www.w3.org/TR/act-rules-format-1.1/)
```

The URL is missing a slash.

2024-07-01 11:59 UTC, remibetin approved these changes

2024-07-02 09:43 UTC, shawna-slh approved these changes

2024-07-02 09:43 UTC, shawna-slh commented
@remibetin ready to publish

2024-07-02 10:25 UTC, merged