Greek – Accessibility Principles
w3c/wai-website pull request #841
Opened 2024-08-22 10:31 UTC by remibetin

Re-creates @Xrisanthi-Mil's https://github.com/w3c/wai-accessibility-principles/pull/48

Resolves https://github.com/w3c/wai-translations/issues/135

2026-02-20 13:15 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Τα εναλλακτικά κείμενα είναι ισοδύναμα για το μη κειμενικό περιεχόμενο. Τα παραδείγματα περιλαμβάνουν.
Test comment

2026-02-26 19:19 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Αυτή η σελίδα εισάγει ορισμένες από τις απαιτήσεις προσβασιμότητας στον Παγκόσμιο Ιστό για ιστότοπους, εφαρμογές Παγκοσμίου Ιστού, προγράμματα περιήγησης και άλλα εργαλεία. Παρέχει αναφορές στα διεθν
Αυτή η σελίδα εισάγει ορισμένες απο τις απαιτήσεις προσβασιμότητας για ιστοτόπους (websites), εφαρμογές (apps), προγράμματα περιήγησης (browsers) και άλλα εργαλεία του Παγκόσμιου Ιστού. Αναφέρεται στα διεθνή πρότυπα του W3C Web Accessibility Initiative (WAI), καθώς και σε ιστορίες χρηστών του ιστού.

2026-02-26 19:30 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η προσβασιμότητα στον Παγκόσμιο Ιστό βασίζεται σε πολλά συστατικά που συνεργάζονται μεταξύ τους. Μερικά από αυτά περιλαμβάνουν:
Η προσβασιμότητα στον ιστό εξαρτάται απο τη συνεργασία διάφορων στοιχείων. Ορισμένα απο αυτά περιλαμβάνουν:

2026-02-26 19:46 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **Περιεχόμενο Παγκοσμίου Ιστού**{:#webcontent} - αναφέρεται σε κάθε τμήμα εντός ιστοτόπου, συμπεριλαμβανομένων του κειμένου, των εικόνων, των φορμών και των πολυμέσων, όπως επίσης οποιουδήποτε κώ
Περιεχόμενο ιστού (web content) - αναφέρεται σε οποιοδήποτε τμήμα ενός ιστοτόπου που περιλαμβάνει κείμενο, εικόνες, φόρμες, πολυμέσα, καθώς και σε οτιδήποτε αφορά κώδικα σήμανσης (markup code), σενάρια (scripts),  εφαρμογές (applications) και άλλα.

2026-02-26 20:13 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **Πράκτορες χρήστη**{:#useragents} - λογισμικό που οι άνθρωποι χρησιμοποιούν για να έχουν πρόσβαση στο περιεχόμενο του Παγκοσμίου Ιστού, συμπεριλαμβανομένων προγράμματα περιήγησης γραφικών για επ
Λογισμικό χρήστη (user agents) - το λογισμικό που χρησιμοποιούν οι άνθρωποι για να έχουν πρόσβαση στο περιεχόμενο του ιστού, συμπεριλαμβανομένων των προγραμμάτων περιηγησης (browsers) γραφικών για επιτραπέζιους υπολογιστές (desktops), των προγραμμάτων περιήγησης μέσω φωνής, των προγραμμάτων περιήγησης για κινητά τηλέφωνα, των προγραμμάτων αναπαραγωγής πολυμέσων, των πρόσθετων (plug-ins), και ορισμένων υποστηρικτικών τεχνολογιών (assistive technologies).

2026-02-26 20:19 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **Εργαλεία συγγραφής**{:#authoringtools} - λογισμικό ή υπηρεσίες που χρησιμοποιούν οι άνθρωποι για την παραγωγή περιεχομένου Παγκοσμίου Ιστού, συμπεριλαμβανομένων προγραμμάτων επεξεργασίας κώδικα
Εργαλεία συγγραφής (Authoring tools) - το λογισμικό ή οι υπηρεσίες που χρησιμοποιούν οι άνθρωποι για την παραγωγή περιεχομένου στον ιστό, συμπεριλαμβανομένων των προγραμμάτων επεξεργασίας κώδικα, των εργαλείων μετατροπής εγγράφων, των συστημάτων διαχείριστης περιεχομένου, των ιστολογίων (blogs), των σεναριών (scripts) για βάσεις δεδομένων, καθώς και άλλων εργαλείων.

2026-02-27 19:56 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +### Περισσότερα σχετικά με τα πρότυπα προσβασιμότητας Παγκοσμίου Iστού
Περισσότερα σχετικά με τα πρότυπα προσβασιμότητας στον ιστό

2026-02-27 19:58 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Αυτά τα στοιχεία αλληλοσυνδέονται και υποστηρίζουν το ένα το άλλο. Για παράδειγμα, το **περιεχόμενο Παγκοσμίου Ιστού** πρέπει να περιλαμβάνει εναλλακτικά κείμενα για εικόνες. Αυτή η πληροφορία πρέπει
1. **περιεχόμενο του ιστού** 
2. "...πρέπει να υποβληθεί σε επεξεργασία απο τα προγράμματα περιηγήσης (web browsers)..."
3. "... όπως οι αναγνώστες οθόνης."
4. "...χρειάζονται τα εργαλεία συγγραφής που τους παρέχουν αυτή τη δυνατότητα."
6. "Περισσότερες πληροφορίες παρέχονται στα Βασικά Στοιχεία για την Προσβασιμότητα στον Ιστό"

2026-02-27 19:59 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Αυτά τα στοιχεία αλληλοσυνδέονται και υποστηρίζουν το ένα το άλλο. Για παράδειγμα, το **περιεχόμενο Παγκοσμίου Ιστού** πρέπει να περιλαμβάνει εναλλακτικά κείμενα για εικόνες. Αυτή η πληροφορία πρέπει
**Which to use when:**
- web = ιστός
- world wide web = παγκόσμιος ιστός

2026-02-27 20:35 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Τα πρότυπα διαδραματίζουν έναν κρίσιμο ρόλο στον καθορισμό των απαιτήσεων προσβασιμότητας για κάθε ένα από αυτά τα συστατικά. Κάποιες απαιτήσεις προσβασιμότητας είναι εύκολο να ικανοποιηθούν, ωστόσο
Τα πρότυπα είναι απαραίτητα για τον καθορισμό των απαιτήσεων προσβασιμότητας σε κάθε ένα απο αυτά τα στοιχεία. Ορισμένες απαιτήσεις προσβασιμότητας είναι εύκολο να ικανοποιηθούν, ωστόσο μια στοιχειώδης γνώση για τον τρόπο με τον οποίο τα άτομα με αναπηρίες χρησιμοποιούν τον Ιστό βοηθά σε μια πιο αποτελεσματική και αποδοτική εφαρμογή τους. Ορισμένες πτυχές της προσβασιμότητας απαιτούν περισσότερες τεχνικές δεξιότητες ή προηγμένες γνώσεις για τον τρόπο με τον οποίο οι άνθρωποι χρησιμοποιούν τον Ιστό. Σε κάθε περίπτωση, η πρώιμη και συνεχής συμμετοχή των χρηστών σε έργα (projects), θα κάνει την δουλεία σας καλύτερη και πιο εύκολη.

2026-02-27 20:39 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η Πρωτοβουλία για τον Παγκόσμιο Ιστό του W3C (WAI) παρέχει ένα σύνολο οδηγιών που αναγνωρίζονται διεθνώς ως το πρότυπο για την προσβασιμότητα στον Παγκόσμιο Ιστό. Αυτά περιλαμβάνουν:
Το W3C Web Accessibility Initiative (WAI) παρέχει ένα σύνολο κατευθυντήριων οδηγιών που αναγνωρίζεται διεθνώς ως πρότυπο για την προσβασιμότητα στον ιστό. Σε αυτές περιλαμβάνονται:

2026-02-27 20:41 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **[Οδηγίες προσβασιμότητας του περιεχομένου του Παγκοσμίου Ιστού (WCAG)](/standards-guidelines/wcag/)**
- Οδηγίες για την Προσβασιμότητα Περιεχομένου στον Ιστό (WCAG)

2026-02-27 20:48 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **[Οδηγίες προσβασιμότητας των πρακτόρων χρήστη (UAAG)](/standards-guidelines/uaag/)**
Οδηγίες για την Προσβασιμότητα Λογισμικού Χρήστη (UAAG)

2026-02-27 20:50 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **[Οδηγίες προσβασιμότητας των εργαλείων συγγραφής (ATAG)](/standards-guidelines/atag/)**
Οδηγίες για την Προσβασιμότητα Εργαλείων Συγγραφής (ATAG)

2026-02-27 21:14 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Υπάρχει επίσης μία προδιαγραφή του WAI για τις **[Προσβάσιμες εμπλουτισμένες εφαρμογές διαδικτύου(WAI-ARIA)](/standards-guidelines/aria/)**, που περιλαμβάνουν δυναμικό περιεχόμενο και προηγμένα στοιχ
Επίσης το WAI έχει ορίσει το πλαίσιο για Προσβάσιμες Πλούσιες Εφαρμογές Διαδικτύου (WAI-ARIA), το οποίο περιλαμβάνει αφενός ένα δυναμικό περιεχόμενο και αφετέρου τα στοιχεία ελέγχου για προηγμένη διεπαφή χρήστη (user interface). Αυτά συνήθως αναπτύσσονται με Ajax, JavaScript, και άλλες σχετικές τεχνολογίες ιστού.

2026-02-27 21:21 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +### Εναλλακτικά κείμενα για μη κειμενικό περιεχόμενο {#alternatives}
Εναλλακτικά κείμενα για μη-κειμενικό περιεχόμενο

2026-03-07 13:50 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Τα εναλλακτικά κείμενα είναι ισοδύναμα για το μη κειμενικό περιεχόμενο. Τα παραδείγματα περιλαμβάνουν.
Τα εναλλακτικά κείμενα είναι ισοδύναμα του μη-κειμενικού περιεχομένου. Για παράδειγμα:

2026-03-07 13:51 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Σύντομα ισοδύναμα για εικόνες, συμπεριλαμβανομένων εικονιδίων, κουμπιών και γραφικών
Οι σύντομες περιγραφές κειμένου για εικόνες, όπως είναι τα εικονίδια, τα κουμπιά και τα γραφικά

2026-03-07 13:55 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Περιγραφή δεδομένων που αναπαρίστανται σε γραφήματα, διαγράμματα και απεικονίσεις
Η περιγραφή δεδομένων που παρουσιάζονται σε γραφήματα, διαγράμματα και εικονογραφήσεις

2026-03-07 13:57 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Σύντομες περιγραφές μη κειμενικού περιεχομένου, όπως αρχεία ήχου και βίντεο
Οι σύντομες περιγραφές για μη-κειμενικό περιεχόμενο, όπως είναι τα αρχεία ήχου και βίντεο

2026-03-07 13:58 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Ετικέτες για στοιχεία ελέγχου φορμών, εισαγωγή δεδομένων
Οι ετικέτες για στοιχεία ελέγχου φορμών, εισαγωγής δεδομένων, καθώς και άλλων στοιχείων διεπαφής

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **Εργαλεία συγγραφής**{:#authoringtools} - λογισμικό ή υπηρεσίες που χρησιμοποιούν οι άνθρωποι για την παραγωγή περιεχομένου Παγκοσμίου Ιστού, συμπεριλαμβανομένων προγραμμάτων επεξεργασίας κώδικα
**final**
Εργαλεία συγγραφής (Authoring tools) - το λογισμικό ή οι υπηρεσίες που χρησιμοποιούν οι άνθρωποι για την παραγωγή περιεχομένου στον ιστό, συμπεριλαμβανομένων των προγραμμάτων επεξεργασίας κώδικα, των εργαλείων μετατροπής εγγράφων, των συστημάτων διαχείριστης περιεχομένου, των ιστολογίων (blogs), των σεναριών (scripts) για βάσεις δεδομένων, καθώς και άλλων εργαλείων.

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **Περιεχόμενο Παγκοσμίου Ιστού**{:#webcontent} - αναφέρεται σε κάθε τμήμα εντός ιστοτόπου, συμπεριλαμβανομένων του κειμένου, των εικόνων, των φορμών και των πολυμέσων, όπως επίσης οποιουδήποτε κώ
**final**
Περιεχόμενο ιστού - αναφέρεται σε οποιοδήποτε τμήμα ενός ιστοτόπου που περιλαμβάνει κείμενο, εικόνες, φόρμες, πολυμέσα, καθώς και σε οτιδήποτε αφορά κώδικα σήμανσης (markup code), σενάρια (scripts), εφαρμογές (applications) και άλλα.

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η προσβασιμότητα στον Παγκόσμιο Ιστό βασίζεται σε πολλά συστατικά που συνεργάζονται μεταξύ τους. Μερικά από αυτά περιλαμβάνουν:
Η προσβασιμότητα στον ιστό βασίζεται σε διάφορα στοιχεία που συνεργάζονται μεταξύ τους. Ορισμένα από αυτά περιλαμβάνουν:

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Αυτή η σελίδα εισάγει ορισμένες από τις απαιτήσεις προσβασιμότητας στον Παγκόσμιο Ιστό για ιστότοπους, εφαρμογές Παγκοσμίου Ιστού, προγράμματα περιήγησης και άλλα εργαλεία. Παρέχει αναφορές στα διεθν
Αυτή η σελίδα εισάγει ορισμένες απο τις απαιτήσεις προσβασιμότητας στον ιστό για ιστοτόπους, διαδικτυακές εφαρμογές, προγράμματα περιήγησης και άλλα εργαλεία. Παρέχει αναφορές στα διεθνή πρότυπα της Πρωτοβουλίας για την Προσβασιμότητα στον Ιστό (WAI) του W3C και σε ιστορίες χρηστών του ιστού.

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **[Οδηγίες προσβασιμότητας του περιεχομένου του Παγκοσμίου Ιστού (WCAG)](/standards-guidelines/wcag/)**
accepted

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **[Οδηγίες προσβασιμότητας των εργαλείων συγγραφής (ATAG)](/standards-guidelines/atag/)**
Accept the change

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **[Οδηγίες προσβασιμότητας των πρακτόρων χρήστη (UAAG)](/standards-guidelines/uaag/)**
Οδηγίες για την Προσβασιμότητα Πρακτόρων Χρήστη (UAAG)

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Ετικέτες για στοιχεία ελέγχου φορμών, εισαγωγή δεδομένων
Accept the change

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +### Εναλλακτικά κείμενα για μη κειμενικό περιεχόμενο {#alternatives}
the Dash might be difficult by web browsers to be read.

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Τα εναλλακτικά κείμενα είναι ισοδύναμα για το μη κειμενικό περιεχόμενο. Τα παραδείγματα περιλαμβάνουν.
**Final**
Τα εναλλακτικά κείμενα είναι ισοδύναμα για το μη κειμενικό περιεχόμενο. Τα παραδείγματα περιλαμβάνουν:

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Σύντομα ισοδύναμα για εικόνες, συμπεριλαμβανομένων εικονιδίων, κουμπιών και γραφικών
-   Σύντομα ισοδύναμα για εικόνες, συμπεριλαμβανομένων εικονιδίων, κουμπιών και γραφικών

It is translated according to the original translation

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Περιγραφή δεδομένων που αναπαρίστανται σε γραφήματα, διαγράμματα και απεικονίσεις
Περιγραφή δεδομένων που παρουσιάζονται σε γραφήματα, διαγράμματα και εικονογραφήσεις

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Σύντομες περιγραφές μη κειμενικού περιεχομένου, όπως αρχεία ήχου και βίντεο
Σύντομες περιγραφές για μη κειμενικό περιεχόμενο, όπως είναι τα αρχεία ήχου και βίντεο

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Υπάρχει επίσης μία προδιαγραφή του WAI για τις **[Προσβάσιμες εμπλουτισμένες εφαρμογές διαδικτύου(WAI-ARIA)](/standards-guidelines/aria/)**, που περιλαμβάνουν δυναμικό περιεχόμενο και προηγμένα στοιχ
Υπάρχει επίσης μία προδιαγραφή του WAI για τις **[Προσβάσιμες Πλούσιες Εφαρμογές Διαδικτύου(WAI-ARIA)](/standards-guidelines/aria/)**, το οποίο περιλαμβάνει δυναμικό περιεχόμενο και προηγμένα στοιχεία ελέγχου διεπαφής χρήστη ανεπτυγμένα με Ajax, JavaScript και σχετικές τεχνολογίες Παγκοσμίου Ιστού.

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η Πρωτοβουλία για τον Παγκόσμιο Ιστό του W3C (WAI) παρέχει ένα σύνολο οδηγιών που αναγνωρίζονται διεθνώς ως το πρότυπο για την προσβασιμότητα στον Παγκόσμιο Ιστό. Αυτά περιλαμβάνουν:
Η Πρωτοβουλία για την Προσβασιμότητα του Ιστού του W3C (WAI) παρέχει ένα σύνολο κατευθυντήριων οδηγιών που αναγνωρίζεται διεθνώς ως το πρότυπο για την προσβασιμότητα στον ιστό. Σε αυτές περιλαμβάνονται:

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Τα πρότυπα διαδραματίζουν έναν κρίσιμο ρόλο στον καθορισμό των απαιτήσεων προσβασιμότητας για κάθε ένα από αυτά τα συστατικά. Κάποιες απαιτήσεις προσβασιμότητας είναι εύκολο να ικανοποιηθούν, ωστόσο
Τα πρότυπα διαδραματίζουν έναν κρίσιμο ρόλο στον καθορισμό των απαιτήσεων προσβασιμότητας για κάθε ένα από αυτά τα στοιχεία. Ορισμένες απαιτήσεις προσβασιμότητας είναι εύκολο να ικανοποιηθούν, ωστόσο η κατανόηση των βασικών αρχών για το πως οι άνθρωποι με αναπηρίες χρησιμοποιούν τον Ιστό βοηθά στο να εφαρμοστούν πιο αποτελεσματικά και αποδοτικά. Ορισμένες πτυχές της προσβασιμότητας απαιτούν περισσότερες τεχνικές δεξιότητες ή προηγμένες γνώσεις για τον τρόπο με τον οποίο οι άνθρωποι χρησιμοποιούν τον Ιστό. Σε κάθε περίπτωση, [η συμμετοχή χρηστών από τα πρώτα στάδια και καθ' όλη τη διάρκεια των διαδικτυακών σας έργων](/test-evaluate/involving-users/) θα κάνει τη δουλειά σας καλύτερη και ευκολότερη.

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Αυτά τα στοιχεία αλληλοσυνδέονται και υποστηρίζουν το ένα το άλλο. Για παράδειγμα, το **περιεχόμενο Παγκοσμίου Ιστού** πρέπει να περιλαμβάνει εναλλακτικά κείμενα για εικόνες. Αυτή η πληροφορία πρέπει
Accepted

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +### Περισσότερα σχετικά με τα πρότυπα προσβασιμότητας Παγκοσμίου Iστού
Accept the change

2026-04-22 19:34 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **Πράκτορες χρήστη**{:#useragents} - λογισμικό που οι άνθρωποι χρησιμοποιούν για να έχουν πρόσβαση στο περιεχόμενο του Παγκοσμίου Ιστού, συμπεριλαμβανομένων προγράμματα περιήγησης γραφικών για επ
Πράκτορες χρήστη (user agents) - το λογισμικό που χρησιμοποιούν οι άνθρωποι για να έχουν πρόσβαση στο περιεχόμενο του ιστού, συμπεριλαμβανομένων των προγραμμάτων περιηγησης γραφικών για επιτραπέζιους υπολογιστές, των προγραμμάτων περιήγησης μέσω φωνής, των προγραμμάτων περιήγησης για κινητά τηλέφωνα, των προγραμμάτων αναπαραγωγής πολυμέσων, των πρόσθετων και ορισμένων υποστηρικτικών τεχνολογιών.

2026-04-23 14:41 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Αυτά τα στοιχεία αλληλοσυνδέονται και υποστηρίζουν το ένα το άλλο. Για παράδειγμα, το **περιεχόμενο Παγκοσμίου Ιστού** πρέπει να περιλαμβάνει εναλλακτικά κείμενα για εικόνες. Αυτή η πληροφορία πρέπει
@avourliotakis @Xrisanthi-Mil Could you provide the full paragraph with modifications? I will then apply the change to the branch.

2026-04-23 14:44 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +### Περισσότερα σχετικά με τα πρότυπα προσβασιμότητας Παγκοσμίου Iστού
I've applied the change. See https://github.com/w3c/wai-website/pull/841/commits/39435ce95140e89b60077907ac8bcdd975820123.

Please let me know if something is wrong.

2026-04-23 14:45 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **[Οδηγίες προσβασιμότητας του περιεχομένου του Παγκοσμίου Ιστού (WCAG)](/standards-guidelines/wcag/)**
I've applied the change. See https://github.com/w3c/wai-website/pull/841/commits/39435ce95140e89b60077907ac8bcdd975820123.

Please let me know if something is wrong.

2026-04-23 14:45 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **[Οδηγίες προσβασιμότητας των εργαλείων συγγραφής (ATAG)](/standards-guidelines/atag/)**
I've applied the change. See https://github.com/w3c/wai-website/pull/841/commits/39435ce95140e89b60077907ac8bcdd975820123.

Please let me know if something is wrong.

2026-04-23 14:45 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Ετικέτες για στοιχεία ελέγχου φορμών, εισαγωγή δεδομένων
I've applied the change. See https://github.com/w3c/wai-website/pull/841/commits/39435ce95140e89b60077907ac8bcdd975820123.

Please let me know if something is wrong.

2026-04-23 21:04 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +**Σημείωση:** Αυτή δεν αποτελεί μια πλήρης λίστα όλων των απαιτήσεων προσβασιμότητας.
Σημείωση: Αυτή δεν αποτελεί μια πλήρη λίστα όλων των απαιτήσεων προσβασιμότητας.

2026-04-23 21:16 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Αυτή η σελίδα εισάγει ορισμένες από τις απαιτήσεις προσβασιμότητας στον Παγκόσμιο Ιστό για ιστότοπους, εφαρμογές Παγκοσμίου Ιστού, προγράμματα περιήγησης και άλλα εργαλεία. Παρέχει αναφορές στα διεθν
@Xrisanthi-Mil 
- το "στον ιστο" προτίμησα να το βάλω στο τέλος της πρώτης πρότασης, καθώς έτσι είναι πιο ευανάγνωστο. Με τα υπόλοιπα συμφωνώ.

2026-04-23 21:34 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **Πράκτορες χρήστη**{:#useragents} - λογισμικό που οι άνθρωποι χρησιμοποιούν για να έχουν πρόσβαση στο περιεχόμενο του Παγκοσμίου Ιστού, συμπεριλαμβανομένων προγράμματα περιήγησης γραφικών για επ
Συμφωνώ με το "πράκτορες χρήστη".

Σημείωση: Οι παρενθέσεις έχουν συμπληρωματικό χαρακτήρα και στοχεύουν στην καλύτερη κατανόηση του περιεχομένου απο τους αναγνώστες. Πολλές λέξεις (κυρίως που αφορούν το web) συνηθίζουμε να τις λέμε στα αγγλικά, όπως πχ. plug-ins, browsers. Αν γίνεται να τις χρησιμοποιούμε συνδυαστικά, όπου χρειάζεται, πιστεύω θα βοηθήσει.

2026-04-23 21:58 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Σύντομα ισοδύναμα για εικόνες, συμπεριλαμβανομένων εικονιδίων, κουμπιών και γραφικών
- Συντομες ισοδύναμες (περιγραφές) για εικόνες, συμπεριλαμβανομένων των εικονιδιών, των κουμπιών και των γραφικών. 

Σημείωση: εδώ το "equivalents" αφορά τις περιγραφες και η συμπληρωματική παρένθεση βοηθά αρκετά στην κατανόηση.

2026-04-23 22:05 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Υπάρχει επίσης μία προδιαγραφή του WAI για τις **[Προσβάσιμες εμπλουτισμένες εφαρμογές διαδικτύου(WAI-ARIA)](/standards-guidelines/aria/)**, που περιλαμβάνουν δυναμικό περιεχόμενο και προηγμένα στοιχ
"η οποία περιλαμβάνει"

2026-04-23 22:07 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η Πρωτοβουλία για τον Παγκόσμιο Ιστό του W3C (WAI) παρέχει ένα σύνολο οδηγιών που αναγνωρίζονται διεθνώς ως το πρότυπο για την προσβασιμότητα στον Παγκόσμιο Ιστό. Αυτά περιλαμβάνουν:
"που αναγνωρίζονται διεθνώς"

2026-04-24 09:20 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Σύντομες περιγραφές μη κειμενικού περιεχομένου, όπως αρχεία ήχου και βίντεο
I've applied the change. See https://github.com/w3c/wai-website/pull/841/commits/ebfe9af0a5a8cf971f8a8cca9303263c6c866674

Please let me know if something is wrong.

2026-04-24 09:20 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Περιγραφή δεδομένων που αναπαρίστανται σε γραφήματα, διαγράμματα και απεικονίσεις
I've applied the change. See https://github.com/w3c/wai-website/commit/ebfe9af0a5a8cf971f8a8cca9303263c6c866674

Please let me know if something is wrong.

2026-04-24 09:20 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **[Οδηγίες προσβασιμότητας των πρακτόρων χρήστη (UAAG)](/standards-guidelines/uaag/)**
I've applied the change. See https://github.com/w3c/wai-website/commit/ebfe9af0a5a8cf971f8a8cca9303263c6c866674

Please let me know if something is wrong.

2026-04-26 11:54 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Αυτή η σελίδα εισάγει ορισμένες από τις απαιτήσεις προσβασιμότητας στον Παγκόσμιο Ιστό για ιστότοπους, εφαρμογές Παγκοσμίου Ιστού, προγράμματα περιήγησης και άλλα εργαλεία. Παρέχει αναφορές στα διεθν
Ok. Let's agree on that. So the final translation is the following:

Αυτή η σελίδα εισάγει ορισμένες απο τις απαιτήσεις προσβασιμότητας για ιστοτόπους, διαδικτυακές εφαρμογές, προγράμματα περιήγησης και άλλα εργαλεία στον ιστό . Παρέχει αναφορές στα διεθνή πρότυπα της Πρωτοβουλίας για την Προσβασιμότητα στον Ιστό (WAI) του W3C και σε ιστορίες χρηστών του ιστού.

2026-04-26 11:57 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **Πράκτορες χρήστη**{:#useragents} - λογισμικό που οι άνθρωποι χρησιμοποιούν για να έχουν πρόσβαση στο περιεχόμενο του Παγκοσμίου Ιστού, συμπεριλαμβανομένων προγράμματα περιήγησης γραφικών για επ
Maybe @remibetin can help us on that.
Should we provide the english version of a word that is commonly used in greek too in a parenthesis. For example browsers is translated "Προγραμματα περιήγησης" in greek. 
In the translation we should keep only the greek word or add the english too in a parenthesis for example   Προγραμματα περιήγησης (browsers)?

2026-04-26 12:03 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Αυτά τα στοιχεία αλληλοσυνδέονται και υποστηρίζουν το ένα το άλλο. Για παράδειγμα, το **περιεχόμενο Παγκοσμίου Ιστού** πρέπει να περιλαμβάνει εναλλακτικά κείμενα για εικόνες. Αυτή η πληροφορία πρέπει
Αυτά τα στοιχεία αλληλοσυνδέονται και υποστηρίζουν το ένα το άλλο. Για παράδειγμα, το **περιεχόμενο του ιστού** πρέπει να περιλαμβάνει εναλλακτικά κείμενα για εικόνες. Αυτή η πληροφορία πρέπει να υποβληθεί σε επεξεργασία από τα **προγράμματα περιήγησης ** και στη συνέχεια να μεταφερθεί σε **υποστηρικτικές τεχνολογίες**, όπως σε αναγνώστες οθόνης. Για να δημιουργήσουν τέτοια εναλλακτικά κείμενα, οι συγγραφείς χρειάζονται τα **εργαλεία συγγραφής** που τους υποστηρίζουν να το κάνουν. Περισσότερες πληροφορίες παρέχονται στα [[Βασικά συστατικά για την Προσβασιμότητα στον Ιστό]](/fundamentals/components/)

2026-04-26 12:04 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η Πρωτοβουλία για τον Παγκόσμιο Ιστό του W3C (WAI) παρέχει ένα σύνολο οδηγιών που αναγνωρίζονται διεθνώς ως το πρότυπο για την προσβασιμότητα στον Παγκόσμιο Ιστό. Αυτά περιλαμβάνουν:
το υποκείμενο είναι το ένα σύνολο. Συνεπώς δε θα έπρεπε να μπει αναγνωρίζεται;

2026-04-26 12:05 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Υπάρχει επίσης μία προδιαγραφή του WAI για τις **[Προσβάσιμες εμπλουτισμένες εφαρμογές διαδικτύου(WAI-ARIA)](/standards-guidelines/aria/)**, που περιλαμβάνουν δυναμικό περιεχόμενο και προηγμένα στοιχ
Accepted so the final translation is:

Υπάρχει επίσης μία προδιαγραφή του WAI για τις [Προσβάσιμες Πλούσιες Εφαρμογές Διαδικτύου(WAI-ARIA)](https://github.com/standards-guidelines/aria/), η οποία περιλαμβάνει δυναμικό περιεχόμενο και προηγμένα στοιχεία ελέγχου διεπαφής χρήστη ανεπτυγμένα με Ajax, JavaScript και σχετικές τεχνολογίες Παγκοσμίου Ιστού.

2026-04-26 12:08 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Σύντομα ισοδύναμα για εικόνες, συμπεριλαμβανομένων εικονιδίων, κουμπιών και γραφικών
Η λέξη περιγραφές είναι πρόσθετη και δεν υπάρχει στο αρχικό κείμενο. Θεωρώ ότι με την προσθήκη παρεμβαίνουμε στο αρχικό κείμενο.

2026-04-26 12:37 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η Πρωτοβουλία για τον Παγκόσμιο Ιστό του W3C (WAI) παρέχει ένα σύνολο οδηγιών που αναγνωρίζονται διεθνώς ως το πρότυπο για την προσβασιμότητα στον Παγκόσμιο Ιστό. Αυτά περιλαμβάνουν:
Σωστά!

2026-04-26 12:41 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι ετικέτες για στοιχεία ελέγχου φορμών, εισαγωγής δεδομένων, καθώς και άλλων στοιχείων διεπαφής
Ας βγάλουμε το άρθρο "Οι" και απο εδώ για λόγους συνέπειας με τα προηγούμενα

2026-04-26 12:53 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Κατευθυντήρια γραμμή Α.3.7: (Για τη διεπαφή χρήστη του εργαλείου συγγραφής) Διασφαλίστε ότι οι προεπισκοπήσεις είναι τουλάχιστον όσο προσβάσιμες όσο στους εντός της αγοράς πράκτορες χρήστη](http
"Διασφαλίστε ότι οι προεσκοπήσεις είναι τουλάχιστον το ίδιο προσβάσιμες και εντός της αγοράς των πρακτόρων χρήστη"

2026-04-26 12:55 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +#### Ιστορίες σχετικές με εναλλακτικά κείμενα
Πιθανά έχουν ανανεωθεί τα links απο αυτή την λίστα. Μεταφράζω τα καινούρια:

- Ade, δημοσιογράφος με περιορισμένη χρήση των χεριών του
- Lakshmi, ανώτερο στέλεχος λογίστρια που είναι τυφλή
- Dhruv, μεγαλύτερος ενήλικας μαθητής που είναι κωφός
- Marta, βοηθός μάρκετινγκ που είναι κωφή και τυφλή
- Stefan, μαθητής με διαταραχή ελλειμματικής προσοχής και υπερκινητικότητας, καθώς και με δυσλεξία
- Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης

2026-04-26 13:24 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +### Το περιεχόμενο είναι ευκολότερο να ιδωθεί και να ακουστεί {#distinguishable}
Εδώ η παθητική φωνή ίσως δυσκολέψει. Αφήνω την ενεργητική εκδοχή μήπως συμφωνήσουμε σε αυτή τελικά:

- Το περιεχόμενο είναι ευκολότερο να το δείτε (ή δεις) και να το ακούσετε (ή ακούσεις)

2026-04-26 13:26 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Το χρώμα δεν χρησιμοποιείται ως ο μοναδικός τρόπος μετάδοσης πληροφορίας ή αναγνώρισης περιεχομένου
Χρώμα που δεν χρησιμοποιείται μόνο για την μετάδοση της πληροφορίας ή αναγνώρισης περιεχομένου

2026-04-26 13:29 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι προεπιλεγμένοι χρωματικοί συνδυασμοί προσκηνίου και παρασκηνίου παρέχουν επαρκή αντίθεση
Προεπιλεγμένους χρωματικούς συνδυασμούς στο προσκήνιο και το παρασκήνιο/φόντο με επαρκή αντίθεση

2026-04-26 13:32 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Όταν οι χρήστες τροποποιούν το μέγεθος κειμένου έως και 400% ή αλλάζουν διάστιχο, δεν υπάρχει απώλεια πληροφορίας
Αλλαγή μεγέθους κειμένου εώς και 400% ή αλλαγή διαστίχου απο τους χρήστες, χωρίς απώλεια της πληροφορίας

2026-04-26 13:35 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Το κείμενο επανακυκλοφορεί σε μικρά παράθυρα ("θύρες προβολής") και όταν οι χρήστες κάνουν το κείμενο μεγαλύτερο
Επαναπροσαρμογή κειμένου σε μικρά παράθυρα ("ορατή περιοχή") και όταν οι χρήστες μεγαλώνουν το κείμενο

2026-04-26 13:39 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι εικόνες κειμένου είναι τροποποιήσιμες ως προς το μέγεθος, αντικαθίστανται με πραγματικό κείμενο ή αποφεύγονται όπου είναι δυνατόν
Εικόνες κειμένου που μπορούν να αλλάξουν μέγεθος, να αντικατασταθούν με πραγματικό κείμενο ή να αποφευγονται όπου είναι δυνατόν

2026-04-26 13:43 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι χρήστες μπορούν να κάνουν παύση, να σταματήσουν ή να προσαρμόσουν την ένταση του ήχου που αναπαράγεται σε έναν ιστότοπο
Χρήστες που μπορούν να κάνουν πάυση, να σταματήσουν ή να προσαρμόσουν την ένταση του ήχου που αναπαράγεται σε έναν ιστότοπο

2026-04-26 13:44 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Ο ήχος στο παρασκήνιο είναι χαμηλός ή μπορεί να απενεργοποιηθεί, για να αποφευχθούν παρεμβολές ή απόσπαση της προσοχής
Ήχο στο παρασκήνιο...

2026-04-26 14:11 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης επιτρέπει στο περιεχόμενο να εκφωνείται σωστά, να μεγεθύνεται ή να προσαρμόζεται ώστε να καλύπτει τις ανάγκες και τις προτιμήσεις διαφορετικών ανθρώπων. Για παράδειγ
Η εκπλήρωση αυτής της απαίτησης επιτρέπει την ορθή εκφώνηση, μεγέθυνση ή προσαρμογή του περιεχομένου, ώστε να ανταποκρίνεται στις ανάγκες και τις προτιμήσεις διαφορετικών ανθρώπων. 

Για να διευκολύνει την ανάγνωση, για παράδειγμα, μπορεί να παρουσιαστεί χρησιμοποιώντας προσαρμοσμένους συνδυασμούς χρωμάτων, μεγέθος κειμένου ή κάποιας άλλης στυλιστικής επιλογής. 

Επίσης η απαίτηση αυτή διευκολύνει και άλλες μορφές προσαρμογής, συμπεριλαμβανομένης της αυτόματης δημιουργίας του περιγράμματος/δομής της σελίδας και των συνόψεων κειμένου, ώστε να βοηθήσει τους χρήστες να έχουν μια σφαιρική εικόνα και να εστιάζουν σε συγκεκριμένα τμήματα πιο εύκολα.

2026-04-26 14:14 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης επιτρέπει στο περιεχόμενο να εκφωνείται σωστά, να μεγεθύνεται ή να προσαρμόζεται ώστε να καλύπτει τις ανάγκες και τις προτιμήσεις διαφορετικών ανθρώπων. Για παράδειγ
Note:
Meet an accessibility requirement = πληρώ μια απαίτηση προσβασιμότητας

2026-04-27 09:10 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Αυτή η σελίδα εισάγει ορισμένες από τις απαιτήσεις προσβασιμότητας στον Παγκόσμιο Ιστό για ιστότοπους, εφαρμογές Παγκοσμίου Ιστού, προγράμματα περιήγησης και άλλα εργαλεία. Παρέχει αναφορές στα διεθν
I've applied the change. See https://github.com/w3c/wai-website/pull/841/commits/7d3d5b3e4d8b098d40e46051e9bf60228383efe9

Please let me know if something is wrong.

2026-04-27 09:10 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Αυτά τα στοιχεία αλληλοσυνδέονται και υποστηρίζουν το ένα το άλλο. Για παράδειγμα, το **περιεχόμενο Παγκοσμίου Ιστού** πρέπει να περιλαμβάνει εναλλακτικά κείμενα για εικόνες. Αυτή η πληροφορία πρέπει
I've applied the change. See https://github.com/w3c/wai-website/commit/7d3d5b3e4d8b098d40e46051e9bf60228383efe9

Please let me know if something is wrong.

2026-04-27 09:11 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Υπάρχει επίσης μία προδιαγραφή του WAI για τις **[Προσβάσιμες εμπλουτισμένες εφαρμογές διαδικτύου(WAI-ARIA)](/standards-guidelines/aria/)**, που περιλαμβάνουν δυναμικό περιεχόμενο και προηγμένα στοιχ
I've applied the change. See https://github.com/w3c/wai-website/commit/7d3d5b3e4d8b098d40e46051e9bf60228383efe9

Please let me know if something is wrong.

2026-04-27 09:32 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **Πράκτορες χρήστη**{:#useragents} - λογισμικό που οι άνθρωποι χρησιμοποιούν για να έχουν πρόσβαση στο περιεχόμενο του Παγκοσμίου Ιστού, συμπεριλαμβανομένων προγράμματα περιήγησης γραφικών για επ
Thanks for asking, @Xrisanthi-Mil.

> In the translation we should keep only the greek word or add the english too in a parenthesis

There is no strict guidance on this. If you expect most people will be familiar with the word in Greek, it's fine to only use Greek. If you consider that adding the English word can help understanding, it's also fine to include the English word in parenthesis.

In such case, make sure to identify the language of this part. For example:
```
Προγραμματα περιήγησης (<span lang="en">browsers</span>)
```

In case it helps, I note that in a [Greek translation of another page](https://www.w3.org/WAI/fundamentals/accessibility-intro/el), "web browsers" was added in parentheses:

> Η προσβασιμότητα στον ιστό εξαρτάται από τη συνεργασία διαφόρων στοιχείων, συμπεριλαμβανομένων των τεχνολογιών ιστού, των προγραμμάτων περιήγησης στον ιστό (web browsers ) και άλλων "user agents", των εργαλείων σύνταξης και των ιστότοπων.

2026-04-27 09:35 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +### Εναλλακτικά κείμενα για μη κειμενικό περιεχόμενο {#alternatives}
@Xrisanthi-Mil @avourliotakis I'm note sure if you've reached an agreement on this part of the translation. If so, could you provide the final translation? Thanks!

2026-06-04 06:38 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +### Εναλλακτικά κείμενα για μη κειμενικό περιεχόμενο {#alternatives}
The final translation is:

Εναλλακτικά κείμενα για μη κειμενικό περιεχόμενο {#alternatives}

2026-06-04 06:44 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +### Το περιεχόμενο είναι ευκολότερο να ιδωθεί και να ακουστεί {#distinguishable}
Απλά ο ενδοιασμός μου είναι ότι δεν έχει χρησιμοποιηθεί καθόλου ο β' ενικός ή β΄ πληθυντικός σε όλη τη μετάφραση. 
Να το δούμε έτσι καλύτερα:
Το περιεχόμενο είναι πιο εύκολο να το δει και να το ακούσει κανείς

2026-06-04 06:47 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Το χρώμα δεν χρησιμοποιείται ως ο μοναδικός τρόπος μετάδοσης πληροφορίας ή αναγνώρισης περιεχομένου
Το διακριτό περιεχόμενο είναι πιο εύκολο να το δει και να το ακούσει κανείς Σε αυτό το περιεχόμενο περιλαμβάνονται τα εξής:
Το χρώμα δεν χρησιμοποιείται ως ο μοναδικός τρόπος μετάδοσης πληροφορίας ή αναγνώρισης περιεχομένου

Γιατί θεωρείς ότι είναι πιο σωστό να βγει το άρθρο;

2026-06-04 06:47 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι προεπιλεγμένοι χρωματικοί συνδυασμοί προσκηνίου και παρασκηνίου παρέχουν επαρκή αντίθεση
Γιατί θεωρείς ότι είναι πιο σωστό να βγει το άρθρο;

2026-06-04 06:47 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Όταν οι χρήστες τροποποιούν το μέγεθος κειμένου έως και 400% ή αλλάζουν διάστιχο, δεν υπάρχει απώλεια πληροφορίας
Γιατί θεωρείς ότι είναι πιο σωστό να βγει το άρθρο;

2026-06-04 06:47 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Το κείμενο επανακυκλοφορεί σε μικρά παράθυρα ("θύρες προβολής") και όταν οι χρήστες κάνουν το κείμενο μεγαλύτερο
Γιατί θεωρείς ότι είναι πιο σωστό να βγει το άρθρο;

2026-06-04 06:47 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι εικόνες κειμένου είναι τροποποιήσιμες ως προς το μέγεθος, αντικαθίστανται με πραγματικό κείμενο ή αποφεύγονται όπου είναι δυνατόν
Γιατί θεωρείς ότι είναι πιο σωστό να βγει το άρθρο;

2026-06-04 06:47 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι χρήστες μπορούν να κάνουν παύση, να σταματήσουν ή να προσαρμόσουν την ένταση του ήχου που αναπαράγεται σε έναν ιστότοπο
Γιατί θεωρείς ότι είναι πιο σωστό να βγει το άρθρο;

2026-06-04 06:52 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης επιτρέπει στο περιεχόμενο να εκφωνείται σωστά, να μεγεθύνεται ή να προσαρμόζεται ώστε να καλύπτει τις ανάγκες και τις προτιμήσεις διαφορετικών ανθρώπων. Για παράδειγ
Η εκπλήρωση αυτής της απαίτησης επιτρέπει στο περιεχόμενο να εκφωνείται σωστά, να μεγεθύνεται ή να προσαρμόζεται ώστε να καλύπτει τις ανάγκες και τις προτιμήσεις διαφορετικών ανθρώπων. Για παράδειγμα, μπορεί να παρουσιαστεί χρησιμοποιώντας προσαρμοσμένους χρωματικούς συνδυασμούς, μέγεθος κειμένου ή άλλο στυλ για διευκόλυνση της ανάγνωσης. Αυτή η απαίτηση διευκολύνει επίσης άλλες μορφές προσαρμογής, συμπεριλαμβανομένης της αυτόματης παραγωγής περιγραμμάτων σελίδας και περιλήψεων ώστε να βοηθηθούν οι άνθρωποι να αποκτήσουν μια σφαιρική εικόνα και να εστιάσουν σε συγκεκριμένα τμήματα πιο εύκολα .

Είναι ωραίος ο τόνος που χρησιμοποιείς αλλά μήπως παρεμβαίνουμε στο αρχικό κείμενο;

2026-06-04 06:54 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +#### Ιστορίες σχετικές με εναλλακτικά κείμενα
**Final**
[Ade, δημοσιογράφος με περιορισμένη χρήση των χεριών του](/people-use-web/user-stories/story-one/)
[Lakshmi, ανώτερο στέλεχος - λογίστρια που είναι τυφλή](/people-use-web/user-stories/story-three/)
[Dhruv, μεγαλύτερος ενήλικας μαθητής που είναι κωφός](/people-use-web/user-stories/story-six/)
[Marta, βοηθός μάρκετινγκ που είναι κωφή και τυφλή](/people-use-web/user-stories/story-seven/)
[Stefan, μαθητής με διαταραχή ελλειμματικής προσοχής και υπερκινητικότητας, καθώς και με δυσλεξία](/people-use-web/user-stories/story-eight/)
[Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης](/people-use-web/user-stories/story-nine/)

2026-06-04 06:55 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Κατευθυντήρια γραμμή Α.3.7: (Για τη διεπαφή χρήστη του εργαλείου συγγραφής) Διασφαλίστε ότι οι προεπισκοπήσεις είναι τουλάχιστον όσο προσβάσιμες όσο στους εντός της αγοράς πράκτορες χρήστη](http
Accepted

2026-06-04 06:56 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι ετικέτες για στοιχεία ελέγχου φορμών, εισαγωγής δεδομένων, καθώς και άλλων στοιχείων διεπαφής
Accepted

2026-06-04 06:56 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +**Σημείωση:** Αυτή δεν αποτελεί μια πλήρης λίστα όλων των απαιτήσεων προσβασιμότητας.
Accepted

2026-06-04 07:00 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **Πράκτορες χρήστη**{:#useragents} - λογισμικό που οι άνθρωποι χρησιμοποιούν για να έχουν πρόσβαση στο περιεχόμενο του Παγκοσμίου Ιστού, συμπεριλαμβανομένων προγράμματα περιήγησης γραφικών για επ
**Final**
Πράκτορες χρήστη (user agents) - το λογισμικό που χρησιμοποιούν οι άνθρωποι για να έχουν πρόσβαση στο περιεχόμενο του ιστού, συμπεριλαμβανομένων των προγραμμάτων περιηγησης (browsers) γραφικών για επιτραπέζιους υπολογιστές (desktops), των προγραμμάτων περιήγησης μέσω φωνής, των προγραμμάτων περιήγησης για κινητά τηλέφωνα, των προγραμμάτων αναπαραγωγής πολυμέσων, των πρόσθετων (plug-ins), και ορισμένων υποστηρικτικών τεχνολογιών (assistive technologies).

2026-06-19 09:10 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η Πρωτοβουλία για τον Παγκόσμιο Ιστό του W3C (WAI) παρέχει ένα σύνολο οδηγιών που αναγνωρίζονται διεθνώς ως το πρότυπο για την προσβασιμότητα στον Παγκόσμιο Ιστό. Αυτά περιλαμβάνουν:
@Xrisanthi-Mil @avourliotakis Have you reached an agreement on this part of the translation? If so, could you provide the final translation? Thanks!

2026-06-19 09:11 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +### Εναλλακτικά κείμενα για μη κειμενικό περιεχόμενο {#alternatives}
@Xrisanthi-Mil Thanks! Since this is the current wording, I'm resolving this comment.

2026-06-19 09:13 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι ετικέτες για στοιχεία ελέγχου φορμών, εισαγωγής δεδομένων, καθώς και άλλων στοιχείων διεπαφής
@Xrisanthi-Mil @avourliotakis Would you please provide the updated phrase?

2026-06-19 09:15 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Κατευθυντήρια γραμμή Α.3.7: (Για τη διεπαφή χρήστη του εργαλείου συγγραφής) Διασφαλίστε ότι οι προεπισκοπήσεις είναι τουλάχιστον όσο προσβάσιμες όσο στους εντός της αγοράς πράκτορες χρήστη](http
Updated, thank you both!

2026-06-19 09:16 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +**Σημείωση:** Αυτή δεν αποτελεί μια πλήρης λίστα όλων των απαιτήσεων προσβασιμότητας.
Updated, thank you both.

2026-06-22 06:02 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι ετικέτες για στοιχεία ελέγχου φορμών, εισαγωγής δεδομένων, καθώς και άλλων στοιχείων διεπαφής
Σύντομα ισοδύναμα για εικόνες, συμπεριλαμβανομένων εικονιδίων, κουμπιών και γραφικών
Περιγραφή δεδομένων που παρουσιάζονται σε γραφήματα, διαγράμματα και εικονογραφήσεις
Σύντομες περιγραφές για μη κειμενικό περιεχόμενο, όπως είναι τα αρχεία ήχου και βίντεο
Ετικέτες για στοιχεία ελέγχου φορμών, εισαγωγής δεδομένων, καθώς και άλλων στοιχείων διεπαφής

2026-06-22 06:03 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η Πρωτοβουλία για τον Παγκόσμιο Ιστό του W3C (WAI) παρέχει ένα σύνολο οδηγιών που αναγνωρίζονται διεθνώς ως το πρότυπο για την προσβασιμότητα στον Παγκόσμιο Ιστό. Αυτά περιλαμβάνουν:
Η Πρωτοβουλία για την Προσβασιμότητα του Ιστού του W3C (WAI) παρέχει ένα σύνολο κατευθυντήριων οδηγιών που αναγνωρίζεται διεθνώς ως το πρότυπο για την προσβασιμότητα στον ιστό. Σε αυτές περιλαμβάνονται:

2026-06-22 08:19 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι ετικέτες για στοιχεία ελέγχου φορμών, εισαγωγής δεδομένων, καθώς και άλλων στοιχείων διεπαφής
I've applied the change. See https://github.com/w3c/wai-website/pull/841/commits/01b1c7487ee853a6727cb1d743da7ab3027abed3

Please let me know if something is wrong.

2026-06-22 08:19 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η Πρωτοβουλία για τον Παγκόσμιο Ιστό του W3C (WAI) παρέχει ένα σύνολο οδηγιών που αναγνωρίζονται διεθνώς ως το πρότυπο για την προσβασιμότητα στον Παγκόσμιο Ιστό. Αυτά περιλαμβάνουν:
I've applied the change. See https://github.com/w3c/wai-website/commit/01b1c7487ee853a6727cb1d743da7ab3027abed3

Please let me know if something is wrong.

2026-06-22 11:26 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Το χρώμα δεν χρησιμοποιείται ως ο μοναδικός τρόπος μετάδοσης πληροφορίας ή αναγνώρισης περιεχομένου
Μου ακούγεται πιο φυσικό με καλύτερη ροή στην ανάγνωση. Ωστόσο δεν αλλάζει σημαντικά αυτό που θέλουμε να επικοινωνήσουμε.

2026-06-22 11:38 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +### Το περιεχόμενο είναι ευκολότερο να ιδωθεί και να ακουστεί {#distinguishable}
I've applied the change. See https://github.com/w3c/wai-website/pull/841/commits/19954f117f4cf5ae2a29501b958fe1b3d1726543

Please let me know if something is wrong.

2026-06-22 11:52 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης επιτρέπει στο περιεχόμενο να εκφωνείται σωστά, να μεγεθύνεται ή να προσαρμόζεται ώστε να καλύπτει τις ανάγκες και τις προτιμήσεις διαφορετικών ανθρώπων. Για παράδειγ
Δεν το θεωρώ παρέμβαση αλλά καλύτερη επικοινωνία στο ελληνικό κοινό. Μπορούμε ωστόσο να το ανεβάσουμε έτσι και το αλλάζουμε μεταγενέστερα

2026-06-22 13:39 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Martine, βαρήκοη εξ' αποστάσεως φοιτήτρια](/people-use-web/user-stories/#onlinestudent)
Να διορθωθούν τα links των user stories:

- Lakshmi, ανώτερο στέλεχος - λογίστρια που είναι τυφλή
- Dhruv, μεγαλύτερος ενήλικας μαθητής που είναι κωφός
- Marta, βοηθός μάρκετινγκ που είναι κωφή και τυφλή

2026-06-22 13:43 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι αλληλουχίες πληροφορίας ή οδηγιών είναι ανεξάρτητες από οποιαδήποτε παρουσίαση
*να είναι

2026-06-22 13:43 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Τα προγράμματα περιήγησης και οι υποστηρικτικές τεχνολογίες παρέχουν ρυθμίσεις για την προσαρμογή της παρουσίασης
*να παρέχουν

2026-06-22 13:45 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Lee, αγοραστής μέσω διαδικτύου με αχρωματοψία](/people-use-web/user-stories/#shopper)
Να μπούν τα updated user stories:

- Ade, δημοσιογράφος με περιορισμένη χρήση των χεριών του
- Lakshmi, ανώτερο στέλεχος λογίστρια που είναι τυφλή
- Dhruv, μεγαλύτερος ενήλικας μαθητής που είναι κωφός
- Marta, βοηθός μάρκετινγκ που είναι κωφή και τυφλή
- Stefan, μαθητής με διαταραχή ελλειμματικής προσοχής και υπερκινητικότητας, καθώς και με δυσλεξία
- Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης

2026-06-22 13:56 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά στο διαχωρισμό του προσκηνίου από το παρασκήνιο, ώστε η σημαντική πληροφορία να γίνει πιο διακριτή . Αυτό περιλαμβάνει σκέψεις για άτομα που δεν χρησιμοποιούν
Η εκπλήρωση αυτής της απαίτησης βοηθά στον διαχωρισμό του προσκηνίου (foreground) από το φόντο (background), ώστε οι σημαντικές πληροφορίες να είναι πιο διακριτές. Αυτό περιλαμβάνει ζητήματα που αφορούν άτομα που δεν χρησιμοποιούν υποστηρικτικές τεχνολογίες και άτομα που χρησιμοποιούν υποστηρικτικές τεχνολογίες και ενδέχεται να παρατηρήσουν παρεμβολές από εμφανές ηχητικό ή οπτικό περιεχόμενο στο φόντο. Για παράδειγμα, πολλά άτομα με αχρωματοψία δεν χρησιμοποιούν συγκεκριμένα εργαλεία και βασίζονται σε έναν κατάλληλο σχεδιασμό που παρέχει επαρκή χρωματική αντίθεση μεταξύ του κειμένου και του περιβάλλοντος φόντου. Για άλλους, ο ήχος που αναπαράγεται αυτόματα θα μπορούσε να επηρεάσει τη μετατροπή κειμένου σε ομιλία ή τις συσκευές ακουστικής υποστήριξης (ALD).

2026-06-22 13:57 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Lee, αγοραστής μέσω διαδικτύου με αχρωματοψία](/people-use-web/user-stories/#shopper)
Το ίδιο και εδώ να γίνουν update

2026-06-22 14:04 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Τα προγράμματα περιήγησης Παγκοσμίου Ιστού, τα εργαλεία συγγραφής και άλλα εργαλεία παρέχουν υποστήριξη μέσω πληκτρολογίου
να βγάλουμε το "παγκοσμιου ιστού" δεν χρειάζεται εδώ

2026-06-22 14:07 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά τους χρήστες πληκτρολογίου, συμπεριλαμβανομένων των ατόμων που χρησιμοποιούν εναλλακτικά πληκτρολόγια, όπως πληκτρολόγια με εργονομική διάταξη, πληκτρολόγια οθ
Η εκπλήρωση αυτής της απαίτησης βοηθά τους χρήστες πληκτρολογίου, συμπεριλαμβανομένων των ατόμων που χρησιμοποιούν εναλλακτικά πληκτρολόγια, όπως πληκτρολόγια με εργονομικές διατάξεις, πληκτρολόγια οθόνης ή συσκευές switch.

2026-06-22 14:08 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Alex, δημοσιογράφος με τραυματισμό επαναλαμβανόμενης καταπόνησης](/people-use-web/user-stories/#reporter)
Το ίδιο και εδώ

2026-06-22 14:16 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι σελίδες έχουν σαφείς τίτλους και είναι οργανωμένες με τη χρήση περιγραφικών επικεφαλίδων ενοτήτων
- με την χρήση περιγραφικών επικεφαλίδων στις ενότητες

2026-06-22 14:22 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Η εστίαση του πληκτρολογίου είναι ορατή και η σειρά εστίασης ακολουθεί μια σειρά με νόημα
- ...και η σειρά της εστίασης ακολουθεί μια αλληλουχία με νόημα

2026-06-22 14:27 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά τους ανθρώπους να πλοηγούνται στις ιστοσελίδες με διαφορετικούς τρόπους, ανάλογα με τις ιδιαίτερες ανάγκες και προτιμήσεις τους. Για παράδειγμα, ενώ μερικοί άν
Η εκπλήρωση αυτής της απαίτησης βοηθά τους ανθρώπους να πλοηγούνται σε ιστοσελίδες με διαφορετικούς τρόπους, ανάλογα με τις ιδιαίτερες ανάγκες και προτιμήσεις τους. Για παράδειγμα, ενώ ορισμένοι βασίζονται σε ιεραρχικές δομές πλοήγησης, όπως είναι οι γραμμές μενού, για να βρουν συγκεκριμένες ιστοσελίδες, άλλοι βασίζονται σε λειτουργίες αναζήτησης σε ιστότοπους. Κάποιοι μπορεί να βλέπουν το περιεχόμενο, ενώ άλλοι μπορεί να το ακούν ή να το βλέπουν και να το ακούν ταυτόχρονα. Κάποιοι μπορεί να χρησιμοποιούν το περιεχόμενο μόνο με ποντίκι ή πληκτρολόγιο, ενώ άλλοι μπορεί να χρησιμοποιούν και τα δύο.

2026-06-22 14:27 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Alex, δημοσιογράφος με τραυματισμό επαναλαμβανόμενης καταπόνησης](/people-use-web/user-stories/#reporter)
το ίδιο

2026-06-22 14:31 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Οι τρόποι εισαγωγής δεδομένων εκτός του πληκτρολογίου, όπως η ενεργοποίηση μέσω αφής, η αναγνώριση φωνής (εισαγωγή ομιλίας) και οι χειρονομίες κάνουν το περιεχόμενο πιο εύκολο στη χρήση από πολλούς α
- * όπως είναι η ενεργοποίηση μέσω αφής.
- * Ορισμένες σχεδιαστικές επιλογές

2026-06-22 14:33 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης καθιστά το περιεχόμενο ευκολότερο στη χρήση για πολλούς ανθρώπους με ένα ευρύ φάσμα ικανοτήτων που χρησιμοποιούν ένα ευρύ φάσμα συσκευών. Αυτό περιλαμβάνει περιεχόμε
Η εκπλήρωση αυτής της απαίτησης καθιστά το περιεχόμενο πιο εύχρηστο για πολλά άτομα με ευρύ φάσμα ικανοτήτων που χρησιμοποιούν ένα ευρύ φάσμα συσκευών. Αυτό περιλαμβάνει περιεχόμενο που χρησιμοποιείται σε κινητά τηλέφωνα, tablet και τερματικά αυτοεξυπηρέτησης, όπως μηχανήματα έκδοσης εισιτηρίων.

2026-06-22 14:33 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Alex, δημοσιογράφος με τραυματισμό επαναλαμβανόμενης καταπόνησης](/people-use-web/user-stories/#reporter)
Το ίδιο

2026-06-22 14:35 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Οι συγγραφείς περιεχομένου πρέπει να διασφαλίζουν ότι το περιεχόμενο κειμένου είναι ευανάγνωστο και κατανοητό στο ευρύτερο δυνατό κοινό, συμπεριλαμβανομένης της ανάγνωσης του δυνατά από λογισμικό κει
- λογισμικό μετατροπής κειμένου σε ομιλία.

2026-06-22 14:36 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά το λογισμικό, συμπεριλαμβανομένης της υποστηρικτικής τεχνολογίας, να επεξεργάζεται σωστά το περιεχόμενο κειμένου. Για παράδειγμα, αυτή η απαίτηση βοηθά το λογι
* εκπλήρωση

2026-06-22 14:36 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Martine, βαρήκοη εξ' αποστάσεως φοιτήτρια](/people-use-web/user-stories/#onlinestudent)
το ίδιο

2026-06-22 14:39 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά τους ανθρώπους να μάθουν γρήγορα τη λειτουργικότητα και τους μηχανισμούς πλοήγησης που παρέχονται σε έναν ιστότοπο και να τους λειτουργούν σύμφωνα με τις συγκε
* εκπλήρωση (παρακαλώ να αλλαχθεί σε όλα)

2026-06-22 14:39 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Alex, δημοσιογράφος με τραυματισμό επαναλαμβανόμενης καταπόνησης](/people-use-web/user-stories/#reporter)
Παρακαλώ να ανενεωθούν σε όλα

2026-06-22 14:42 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Βοήθεια ευαίσθητη ως προς το γενικότερο πλαίσιο για πιο σύνθετη λειτουργικότητα και αλληλεπίδραση
- Σχετική βοήθεια ως προς το γενικότερο πλαίσιο

2026-06-22 14:45 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά στη μεγιστοποίηση της συμβατότητας με τους τρέχοντες και τους μελλοντικούς πράκτορες χρήστη, συμπεριλαμβανομένων των υποστηρικτικών τεχνολογιών. Συγκεκριμένα,
Με τις παραπάνω αλλαγές νομίζω ότι το κείμενο είναι σε ένα αξιόλογο επίπεδο. Πάντοτε υπάρχει χώρος για βελτίωση, αλλά προς το παρόν είμαστε οκ.

2026-06-23 06:09 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Βοήθεια ευαίσθητη ως προς το γενικότερο πλαίσιο για πιο σύνθετη λειτουργικότητα και αλληλεπίδραση
**Final**
Οι φόρμες και άλλες αλληλεπιδράσεις μπορεί να προκαλούν σύγχυση ή δυσκολία στη χρήση για πολλούς ανθρώπους και, ως αποτέλεσμα, μπορεί να είναι πιο πιθανό αυτοί να κάνουν λάθη. Παραδείγματα που βοηθούν τους χρήστες να αποφύγουν και να διορθώσουν λάθη περιλαμβάνουν:

-   Περιγραφικές οδηγίες, μηνύματα λάθους και προτάσεις για διόρθωση
-   Σχετική βοήθεια ως προς το γενικότερο πλαίσιο για πιο σύνθετη λειτουργικότητα και αλληλεπίδραση

2026-06-23 06:11 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Σύντομα ισοδύναμα για εικόνες, συμπεριλαμβανομένων εικονιδίων, κουμπιών και γραφικών
**Final**
Τα εναλλακτικά κείμενα είναι ισοδύναμα για το μη κειμενικό περιεχόμενο. Τα παραδείγματα περιλαμβάνουν.

-   Σύντομα ισοδύναμα για εικόνες, συμπεριλαμβανομένων εικονιδίων, κουμπιών και γραφικών

2026-06-23 06:12 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι αλληλουχίες πληροφορίας ή οδηγιών είναι ανεξάρτητες από οποιαδήποτε παρουσίαση
**Final**
Για να μπορούν οι χρήστες να αλλάζουν την παρουσίαση του περιεχομένου, είναι απαραίτητο:

-   Οι επικεφαλίδες, οι λίστες, οι πίνακες, τα πεδία εισαγωγής δεδομένων και οι δομές περιεχομένου να επισημαίνονται σωστά
-   Οι αλληλουχίες πληροφορίας ή οδηγιών να είναι ανεξάρτητες από οποιαδήποτε παρουσίαση

2026-06-23 06:12 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Τα προγράμματα περιήγησης και οι υποστηρικτικές τεχνολογίες παρέχουν ρυθμίσεις για την προσαρμογή της παρουσίασης
**final**
-   Οι επικεφαλίδες, οι λίστες, οι πίνακες, τα πεδία εισαγωγής δεδομένων και οι δομές περιεχομένου να επισημαίνονται σωστά
-   Οι αλληλουχίες πληροφορίας ή οδηγιών είναι ανεξάρτητες από οποιαδήποτε παρουσίαση
-   Τα προγράμματα περιήγησης και οι υποστηρικτικές τεχνολογίες να παρέχουν ρυθμίσεις για την προσαρμογή της παρουσίασης

2026-06-23 06:15 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Lee, αγοραστής μέσω διαδικτύου με αχρωματοψία](/people-use-web/user-stories/#shopper)
Accepted (user stories changed)

2026-06-23 06:24 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Martine, βαρήκοη εξ' αποστάσεως φοιτήτρια](/people-use-web/user-stories/#onlinestudent)
**Final**
Lakshmi, ανώτερο στέλεχος - λογίστρια που είναι τυφλή(/people-use-web/user-stories/story-three/)
Dhruv, μεγαλύτερος ενήλικας μαθητής που είναι κωφός(/people-use-web/user-stories/story-six/)
Marta, βοηθός μάρκετινγκ που είναι κωφή και τυφλή(/people-use-web/user-stories/story-seven/)

2026-06-23 06:25 UTC, Xrisanthi-Mil requested changes

2026-06-23 06:27 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης επιτρέπει στο περιεχόμενο να εκφωνείται σωστά, να μεγεθύνεται ή να προσαρμόζεται ώστε να καλύπτει τις ανάγκες και τις προτιμήσεις διαφορετικών ανθρώπων. Για παράδειγ
**Final**
Η εκπλήρωση αυτής της απαίτησης επιτρέπει στο περιεχόμενο να εκφωνείται σωστά, να μεγεθύνεται ή να προσαρμόζεται ώστε να καλύπτει τις ανάγκες και τις προτιμήσεις διαφορετικών ανθρώπων. Για παράδειγμα, μπορεί να παρουσιαστεί χρησιμοποιώντας προσαρμοσμένους χρωματικούς συνδυασμούς, μέγεθος κειμένου ή άλλο στυλ για διευκόλυνση της ανάγνωσης. Αυτή η απαίτηση διευκολύνει επίσης άλλες μορφές προσαρμογής, συμπεριλαμβανομένης της αυτόματης παραγωγής περιγραμμάτων σελίδας και περιλήψεων ώστε να βοηθηθούν οι άνθρωποι να αποκτήσουν μια σφαιρική εικόνα και να εστιάσουν σε συγκεκριμένα τμήματα πιο εύκολα .

2026-06-23 06:28 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι προεπιλεγμένοι χρωματικοί συνδυασμοί προσκηνίου και παρασκηνίου παρέχουν επαρκή αντίθεση
**Final**
Οι προεπιλεγμένοι χρωματικοί συνδυασμοί προσκηνίου και παρασκηνίου παρέχουν επαρκή αντίθεση

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Το χρώμα δεν χρησιμοποιείται ως ο μοναδικός τρόπος μετάδοσης πληροφορίας ή αναγνώρισης περιεχομένου
**Final**
Το χρώμα δεν χρησιμοποιείται ως ο μοναδικός τρόπος μετάδοσης πληροφορίας ή αναγνώρισης περιεχομένου

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Όταν οι χρήστες τροποποιούν το μέγεθος κειμένου έως και 400% ή αλλάζουν διάστιχο, δεν υπάρχει απώλεια πληροφορίας
**final**
Όταν οι χρήστες τροποποιούν το μέγεθος κειμένου έως και 400% ή αλλάζουν διάστιχο, δεν υπάρχει απώλεια πληροφορίας

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι εικόνες κειμένου είναι τροποποιήσιμες ως προς το μέγεθος, αντικαθίστανται με πραγματικό κείμενο ή αποφεύγονται όπου είναι δυνατόν
**final**
Οι εικόνες κειμένου μπορούν να αλλάξουν μέγεθος, να αντικατασταθούν με πραγματικό κείμενο ή να αποφεύγονται όπου είναι δυνατόν

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι χρήστες μπορούν να κάνουν παύση, να σταματήσουν ή να προσαρμόσουν την ένταση του ήχου που αναπαράγεται σε έναν ιστότοπο
**final**
Οι χρήστες μπορούν να κάνουν παύση, να σταματήσουν ή να προσαρμόσουν την ένταση του ήχου που αναπαράγεται σε έναν ιστότοπο

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Ο ήχος στο παρασκήνιο είναι χαμηλός ή μπορεί να απενεργοποιηθεί, για να αποφευχθούν παρεμβολές ή απόσπαση της προσοχής
**final**
Ο ήχος στο παρασκήνιο είναι χαμηλός ή μπορεί να απενεργοποιηθεί, για να αποφευχθούν παρεμβολές ή απόσπαση της προσοχής

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά στο διαχωρισμό του προσκηνίου από το παρασκήνιο, ώστε η σημαντική πληροφορία να γίνει πιο διακριτή . Αυτό περιλαμβάνει σκέψεις για άτομα που δεν χρησιμοποιούν
Accepted

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Lee, αγοραστής μέσω διαδικτύου με αχρωματοψία](/people-use-web/user-stories/#shopper)
**final**
[Ian, υπάλληλος καταχώρισης δεδομένων με αυτισμό](/people-use-web/user-stories/story-two/)
[Lakshmi, ανώτερο στέλεχος - λογίστρια που είναι τυφλή](/people-use-web/user-stories/story-three/)
[Lexie, καταναλώτρια που πραγματοποιεί αγορές μέσω διαδικτύου που δυσκολεύεται να διακρίνει ορισμένα χρώματα (αχρωματοψία)](https://www.w3.org/WAI/people-use-web/user-stories/story-four/)
[Dhruv, μεγαλύτερος ενήλικας μαθητής που είναι κωφός](/people-use-web/user-stories/story-six/)
[Marta, βοηθός μάρκετινγκ που είναι κωφή και τυφλή](/people-use-web/user-stories/story-seven/)
[Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης](/people-use-web/user-stories/story-nine/)

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Lee, αγοραστής μέσω διαδικτύου με αχρωματοψία](/people-use-web/user-stories/#shopper)
[Ade, δημοσιογράφος με περιορισμένη χρήση των χεριών του](/people-use-web/user-stories/story-one/)
[Lakshmi, ανώτερο στέλεχος - λογίστρια που είναι τυφλή](/people-use-web/user-stories/story-three/)
[Dhruv, μεγαλύτερος ενήλικας μαθητής που είναι κωφός](/people-use-web/user-stories/story-six/)
[Marta, βοηθός μάρκετινγκ που είναι κωφή και τυφλή](/people-use-web/user-stories/story-seven/)
[Stefan, μαθητής με διαταραχή ελλειμματικής προσοχής και υπερκινητικότητας, καθώς και με δυσλεξία](/people-use-web/user-stories/story-eight/)
[Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης](/people-use-web/user-stories/story-nine/)

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Το κείμενο επανακυκλοφορεί σε μικρά παράθυρα ("θύρες προβολής") και όταν οι χρήστες κάνουν το κείμενο μεγαλύτερο
**final**
Το κείμενο επαναπροσαρμόζεται σε μικρά παράθυρα ("ορατή περιοχή") και όταν οι χρήστες μεγαλώνουν το κείμενο

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Τα προγράμματα περιήγησης Παγκοσμίου Ιστού, τα εργαλεία συγγραφής και άλλα εργαλεία παρέχουν υποστήριξη μέσω πληκτρολογίου
Accepted
Τα προγράμματα περιήγησης, τα εργαλεία συγγραφής και άλλα εργαλεία παρέχουν υποστήριξη μέσω πληκτρολογίου

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά τους χρήστες πληκτρολογίου, συμπεριλαμβανομένων των ατόμων που χρησιμοποιούν εναλλακτικά πληκτρολόγια, όπως πληκτρολόγια με εργονομική διάταξη, πληκτρολόγια οθ
Accepted
Η εκπλήρωση αυτής της απαίτησης βοηθά τους χρήστες πληκτρολογίου, συμπεριλαμβανομένων των ατόμων που χρησιμοποιούν εναλλακτικά πληκτρολόγια, όπως πληκτρολόγια με εργονομική διάταξη, πληκτρολόγια οθόνης ή συσκευές διακοπτών (switch). Βοηθά επίσης άτομα που χρησιμοποιούν φωνητική αναγνώριση (εισαγωγή ομιλίας) να χειρίζονται ιστότοπους και να υπαγορεύουν κείμενο μέσω της διεπαφής του πληκτρολογίου.

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Alex, δημοσιογράφος με τραυματισμό επαναλαμβανόμενης καταπόνησης](/people-use-web/user-stories/#reporter)
[Ade, δημοσιογράφος με περιορισμένη χρήση των χεριών του](/people-use-web/user-stories/story-one/)
[Lakshmi, ανώτερο στέλεχος - λογίστρια που είναι τυφλή](/people-use-web/user-stories/story-three/)

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι σελίδες έχουν σαφείς τίτλους και είναι οργανωμένες με τη χρήση περιγραφικών επικεφαλίδων ενοτήτων
**final**
Οι σελίδες έχουν σαφείς τίτλους και είναι οργανωμένες με τη χρήση περιγραφικών επικεφαλίδων στις ενότητες

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Η εστίαση του πληκτρολογίου είναι ορατή και η σειρά εστίασης ακολουθεί μια σειρά με νόημα
Accepted
Η εστίαση του πληκτρολογίου είναι ορατή και η και η σειρά της εστίασης ακολουθεί μια αλληλουχία με νόημα

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά τους ανθρώπους να πλοηγούνται στις ιστοσελίδες με διαφορετικούς τρόπους, ανάλογα με τις ιδιαίτερες ανάγκες και προτιμήσεις τους. Για παράδειγμα, ενώ μερικοί άν
Accepted

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Alex, δημοσιογράφος με τραυματισμό επαναλαμβανόμενης καταπόνησης](/people-use-web/user-stories/#reporter)
[Ade, δημοσιογράφος με περιορισμένη χρήση των χεριών του](/people-use-web/user-stories/story-one/)
[Ian, υπάλληλος καταχώρισης δεδομένων με αυτισμό](/people-use-web/user-stories/story-two/)
[Lakshmi, ανώτερο στέλεχος - λογίστρια που είναι τυφλή](/people-use-web/user-stories/story-three/)
[Sophie, φίλαθλος της καλαθοσφαίρισης με σύνδρομο Down](/people-use-web/user-stories/story-five/)
[Marta, βοηθός μάρκετινγκ που είναι κωφή και τυφλή](/people-use-web/user-stories/story-seven/)
[Stefan, μαθητής με διαταραχή ελλειμματικής προσοχής και υπερκινητικότητας, καθώς και με δυσλεξία](/people-use-web/user-stories/story-eight/)
[Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης](/people-use-web/user-stories/story-nine/)

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Οι τρόποι εισαγωγής δεδομένων εκτός του πληκτρολογίου, όπως η ενεργοποίηση μέσω αφής, η αναγνώριση φωνής (εισαγωγή ομιλίας) και οι χειρονομίες κάνουν το περιεχόμενο πιο εύκολο στη χρήση από πολλούς α
**final**
Οι τρόποι εισαγωγής δεδομένων εκτός του πληκτρολογίου, όπως είναι η ενεργοποίηση μέσω αφής, η αναγνώριση φωνής (εισαγωγή ομιλίας) και οι χειρονομίες κάνουν το περιεχόμενο πιο εύκολο στη χρήση από πολλούς ανθρώπους. Ωστόσο, δεν μπορούν όλοι να χρησιμοποιήσουν καθεμία από αυτές τις μεθόδους εισαγωγής δεδομένων και στον ίδιο βαθμό. Ορισμένες σχεδιαστικές επιλογές μεγιστοποιούν το όφελος αυτών των τρόπων εισαγωγής δεδομένων. Αυτό περιλαμβάνει:

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης καθιστά το περιεχόμενο ευκολότερο στη χρήση για πολλούς ανθρώπους με ένα ευρύ φάσμα ικανοτήτων που χρησιμοποιούν ένα ευρύ φάσμα συσκευών. Αυτό περιλαμβάνει περιεχόμε
accepted

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Alex, δημοσιογράφος με τραυματισμό επαναλαμβανόμενης καταπόνησης](/people-use-web/user-stories/#reporter)
Ade, δημοσιογράφος με περιορισμένη χρήση των χεριών του (/people-use-web/user-stories/story-one/)
Sophie, φίλαθλος της καλαθοσφαίρισης με σύνδρομο Down(/people-use-web/user-stories/story-five/)
Stefan, μαθητής με διαταραχή ελλειμματικής προσοχής και υπερκινητικότητας, καθώς και με δυσλεξία (/people-use-web/user-stories/story-eight/)
Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης (/people-use-web/user-stories/story-nine/)

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Οι συγγραφείς περιεχομένου πρέπει να διασφαλίζουν ότι το περιεχόμενο κειμένου είναι ευανάγνωστο και κατανοητό στο ευρύτερο δυνατό κοινό, συμπεριλαμβανομένης της ανάγνωσης του δυνατά από λογισμικό κει
**final**
Οι συγγραφείς περιεχομένου πρέπει να διασφαλίζουν ότι το περιεχόμενο κειμένου είναι ευανάγνωστο και κατανοητό στο ευρύτερο δυνατό κοινό, συμπεριλαμβανομένης της ανάγνωσης του δυνατά από λογισμικό μετατροπής κειμένου σε ομιλία. Τέτοιο περιεχόμενο περιλαμβάνει:

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά το λογισμικό, συμπεριλαμβανομένης της υποστηρικτικής τεχνολογίας, να επεξεργάζεται σωστά το περιεχόμενο κειμένου. Για παράδειγμα, αυτή η απαίτηση βοηθά το λογι
Η εκπλήρωση αυτής της απαίτησης βοηθά το λογισμικό, συμπεριλαμβανομένης της υποστηρικτικής τεχνολογίας, να επεξεργάζεται σωστά το περιεχόμενο κειμένου. Για παράδειγμα, αυτή η απαίτηση βοηθά το λογισμικό να διαβάζει το περιεχόμενο δυνατά, να παράγει περιλήψεις σελίδων και να παρέχει ορισμούς για ασυνήθιστες λέξεις, όπως η τεχνική ορολογία. Βοηθά επίσης άτομα που δυσκολεύονται να κατανοήσουν πιο σύνθετες προτάσεις, φράσεις και λεξιλόγιο. Συγκεκριμένα, βοηθά ανθρώπους με διαφορετικούς τύπους γνωσιακών αναπηριών.

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Martine, βαρήκοη εξ' αποστάσεως φοιτήτρια](/people-use-web/user-stories/#onlinestudent)
[Ian, υπάλληλος καταχώρισης δεδομένων με αυτισμό](/people-use-web/user-stories/story-two/)
[Lakshmi, ανώτερο στέλεχος - λογίστρια που είναι τυφλή](/people-use-web/user-stories/story-three/)
[Sophie, φίλαθλος της καλαθοσφαίρισης με σύνδρομο Down](/people-use-web/user-stories/story-five/)
[Dhruv, μεγαλύτερος ενήλικας μαθητής που είναι κωφός](/people-use-web/user-stories/story-six/)
[Stefan, μαθητής με διαταραχή ελλειμματικής προσοχής και υπερκινητικότητας, καθώς και με δυσλεξία](/people-use-web/user-stories/story-eight/)
[Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης](/people-use-web/user-stories/story-nine/)

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά τους ανθρώπους να μάθουν γρήγορα τη λειτουργικότητα και τους μηχανισμούς πλοήγησης που παρέχονται σε έναν ιστότοπο και να τους λειτουργούν σύμφωνα με τις συγκε
**final**
Η εκπλήρωση αυτής της απαίτησης βοηθά τους ανθρώπους να μάθουν γρήγορα τη λειτουργικότητα και τους μηχανισμούς πλοήγησης που παρέχονται σε έναν ιστότοπο και να τους λειτουργούν σύμφωνα με τις συγκεκριμένες ανάγκες και προτιμήσεις τους. Για παράδειγμα, κάποιοι άνθρωποι αναθέτουν εξατομικευμένα πλήκτρα συντόμευσης σε λειτουργίες που χρησιμοποιούν συχνά για να βελτιώσουν την πλοήγηση με πληκτρολόγιο. Άλλοι απομνημονεύουν τα βήματα για να φτάσουν σε συγκεκριμένες σελίδες ή να ολοκληρώσουν διαδικασίες σε έναν ιστότοπο. Και οι δύο βασίζονται σε προβλέψιμη και συνεπή λειτουργικότητα.

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Alex, δημοσιογράφος με τραυματισμό επαναλαμβανόμενης καταπόνησης](/people-use-web/user-stories/#reporter)
[Ade, δημοσιογράφος με περιορισμένη χρήση των χεριών του](/people-use-web/user-stories/story-one/)
[Ian, υπάλληλος καταχώρισης δεδομένων με αυτισμό](/people-use-web/user-stories/story-two/)
[Lakshmi, ανώτερο στέλεχος - λογίστρια που είναι τυφλή](/people-use-web/user-stories/story-three/)
[Sophie, φίλαθλος της καλαθοσφαίρισης με σύνδρομο Down](/people-use-web/user-stories/story-five/)
[Marta, βοηθός μάρκετινγκ που είναι κωφή και τυφλή](/people-use-web/user-stories/story-seven/)
[Stefan, μαθητής με διαταραχή ελλειμματικής προσοχής και υπερκινητικότητας, καθώς και με δυσλεξία](/people-use-web/user-stories/story-eight/)
[Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης](/people-use-web/user-stories/story-nine/)

2026-06-23 07:07 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά στη μεγιστοποίηση της συμβατότητας με τους τρέχοντες και τους μελλοντικούς πράκτορες χρήστη, συμπεριλαμβανομένων των υποστηρικτικών τεχνολογιών. Συγκεκριμένα,
@remibetin this is the final comment from @avourliotakis 
"With the above changes, I think the text is at a very good level. There is always room for improvement, but for the time being, we're good."

2026-06-23 09:31 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η προσβασιμότητα στον Παγκόσμιο Ιστό βασίζεται σε πολλά συστατικά που συνεργάζονται μεταξύ τους. Μερικά από αυτά περιλαμβάνουν:
I've applied the change. See https://github.com/w3c/wai-website/pull/841/commits/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:34 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Martine, βαρήκοη εξ' αποστάσεως φοιτήτρια](/people-use-web/user-stories/#onlinestudent)
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:34 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Τα προγράμματα περιήγησης και οι υποστηρικτικές τεχνολογίες παρέχουν ρυθμίσεις για την προσαρμογή της παρουσίασης
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:34 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Lee, αγοραστής μέσω διαδικτύου με αχρωματοψία](/people-use-web/user-stories/#shopper)
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:34 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά στο διαχωρισμό του προσκηνίου από το παρασκήνιο, ώστε η σημαντική πληροφορία να γίνει πιο διακριτή . Αυτό περιλαμβάνει σκέψεις για άτομα που δεν χρησιμοποιούν
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:34 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Τα προγράμματα περιήγησης Παγκοσμίου Ιστού, τα εργαλεία συγγραφής και άλλα εργαλεία παρέχουν υποστήριξη μέσω πληκτρολογίου
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:34 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά τους χρήστες πληκτρολογίου, συμπεριλαμβανομένων των ατόμων που χρησιμοποιούν εναλλακτικά πληκτρολόγια, όπως πληκτρολόγια με εργονομική διάταξη, πληκτρολόγια οθ
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:34 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι σελίδες έχουν σαφείς τίτλους και είναι οργανωμένες με τη χρήση περιγραφικών επικεφαλίδων ενοτήτων
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:34 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Η εστίαση του πληκτρολογίου είναι ορατή και η σειρά εστίασης ακολουθεί μια σειρά με νόημα
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:34 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά τους ανθρώπους να πλοηγούνται στις ιστοσελίδες με διαφορετικούς τρόπους, ανάλογα με τις ιδιαίτερες ανάγκες και προτιμήσεις τους. Για παράδειγμα, ενώ μερικοί άν
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:35 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Alex, δημοσιογράφος με τραυματισμό επαναλαμβανόμενης καταπόνησης](/people-use-web/user-stories/#reporter)
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:35 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Οι τρόποι εισαγωγής δεδομένων εκτός του πληκτρολογίου, όπως η ενεργοποίηση μέσω αφής, η αναγνώριση φωνής (εισαγωγή ομιλίας) και οι χειρονομίες κάνουν το περιεχόμενο πιο εύκολο στη χρήση από πολλούς α
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:35 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Alex, δημοσιογράφος με τραυματισμό επαναλαμβανόμενης καταπόνησης](/people-use-web/user-stories/#reporter)
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:35 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Οι συγγραφείς περιεχομένου πρέπει να διασφαλίζουν ότι το περιεχόμενο κειμένου είναι ευανάγνωστο και κατανοητό στο ευρύτερο δυνατό κοινό, συμπεριλαμβανομένης της ανάγνωσης του δυνατά από λογισμικό κει
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:35 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά το λογισμικό, συμπεριλαμβανομένης της υποστηρικτικής τεχνολογίας, να επεξεργάζεται σωστά το περιεχόμενο κειμένου. Για παράδειγμα, αυτή η απαίτηση βοηθά το λογι
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:35 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά τους ανθρώπους να μάθουν γρήγορα τη λειτουργικότητα και τους μηχανισμούς πλοήγησης που παρέχονται σε έναν ιστότοπο και να τους λειτουργούν σύμφωνα με τις συγκε
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:35 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Alex, δημοσιογράφος με τραυματισμό επαναλαμβανόμενης καταπόνησης](/people-use-web/user-stories/#reporter)
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:35 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Βοήθεια ευαίσθητη ως προς το γενικότερο πλαίσιο για πιο σύνθετη λειτουργικότητα και αλληλεπίδραση
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:36 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης βοηθά στη μεγιστοποίηση της συμβατότητας με τους τρέχοντες και τους μελλοντικούς πράκτορες χρήστη, συμπεριλαμβανομένων των υποστηρικτικών τεχνολογιών. Συγκεκριμένα,
@Xrisanthi-Mil @avourliotakis Thank you for your collaborative work on this!

2026-06-23 09:36 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Martine, βαρήκοη εξ' αποστάσεως φοιτήτρια](/people-use-web/user-stories/#onlinestudent)
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:36 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης καθιστά το περιεχόμενο ευκολότερο στη χρήση για πολλούς ανθρώπους με ένα ευρύ φάσμα ικανοτήτων που χρησιμοποιούν ένα ευρύ φάσμα συσκευών. Αυτό περιλαμβάνει περιεχόμε
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:36 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Alex, δημοσιογράφος με τραυματισμό επαναλαμβανόμενης καταπόνησης](/people-use-web/user-stories/#reporter)
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:36 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   [Lee, αγοραστής μέσω διαδικτύου με αχρωματοψία](/people-use-web/user-stories/#shopper)
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:36 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι αλληλουχίες πληροφορίας ή οδηγιών είναι ανεξάρτητες από οποιαδήποτε παρουσίαση
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:38 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   **Εργαλεία συγγραφής**{:#authoringtools} - λογισμικό ή υπηρεσίες που χρησιμοποιούν οι άνθρωποι για την παραγωγή περιεχομένου Παγκοσμίου Ιστού, συμπεριλαμβανομένων προγραμμάτων επεξεργασίας κώδικα
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:40 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Σύντομα ισοδύναμα για εικόνες, συμπεριλαμβανομένων εικονιδίων, κουμπιών και γραφικών
Thanks, @Xrisanthi-Mil and @avourliotakis. I understand no changes were made to this line. 

Please let me know if I missed a requested change.

2026-06-23 09:42 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +- [[Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης]](/people-use-web/user-stories/story-nine/)
In these 6 rows there is double [[ and double ]]

2026-06-23 09:42 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +
In these 3 rows there is double [[ and double ]]

2026-06-23 09:42 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +- [[Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης]](/people-use-web/user-stories/story-nine/)
In these 6 rows there is double [[ and double ]]

2026-06-23 09:43 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +- [[Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης]](/people-use-web/user-stories/story-nine/)
In these 6 rows there is double [[ and double ]]

2026-06-23 09:43 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
In these 6 rows there is double [[ and double ]]

2026-06-23 09:43 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +- [[Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης]](/people-use-web/user-stories/story-nine/)
In these 7 rows there is double [[ and double ]]

2026-06-23 09:43 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +- [[Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης]](/people-use-web/user-stories/story-nine/)
In these 4 rows there is double [[ and double ]]

2026-06-23 09:43 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +- [[Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης]](/people-use-web/user-stories/story-nine/)
In these 6 rows there is double [[ and double ]]

2026-06-23 09:43 UTC, Xrisanthi-Mil commented on pages/fundamentals/accessibility-principles/index.el.md
> +- [[Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης]](/people-use-web/user-stories/story-nine/)
In these 7 rows there is double [[ and double ]]

2026-06-23 09:46 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +#### Ιστορίες σχετικές με εναλλακτικά κείμενα
I've applied the change. See https://github.com/w3c/wai-website/commit/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:47 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Το χρώμα δεν χρησιμοποιείται ως ο μοναδικός τρόπος μετάδοσης πληροφορίας ή αναγνώρισης περιεχομένου
@Xrisanthi-Mil I understand no changes were finally made to this line. Please let me know if I missed a requested change.

2026-06-23 09:48 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι προεπιλεγμένοι χρωματικοί συνδυασμοί προσκηνίου και παρασκηνίου παρέχουν επαρκή αντίθεση
@Xrisanthi-Mil I understand that no changes were finally made to this line. Please let me know if I missed a requested change. cc @avourliotakis

2026-06-23 09:51 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Όταν οι χρήστες τροποποιούν το μέγεθος κειμένου έως και 400% ή αλλάζουν διάστιχο, δεν υπάρχει απώλεια πληροφορίας
@Xrisanthi-Mil I understand that no changes were finally made to this line. Please let me know if I missed a requested change. cc @avourliotakis

2026-06-23 09:55 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Το κείμενο επανακυκλοφορεί σε μικρά παράθυρα ("θύρες προβολής") και όταν οι χρήστες κάνουν το κείμενο μεγαλύτερο
I've applied the change. See https://github.com/w3c/wai-website/pull/841/commits/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:56 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Η ικανοποίηση αυτής της απαίτησης επιτρέπει στο περιεχόμενο να εκφωνείται σωστά, να μεγεθύνεται ή να προσαρμόζεται ώστε να καλύπτει τις ανάγκες και τις προτιμήσεις διαφορετικών ανθρώπων. Για παράδειγ
I've applied the change. See https://github.com/w3c/wai-website/pull/841/commits/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:57 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Οι εικόνες κειμένου είναι τροποποιήσιμες ως προς το μέγεθος, αντικαθίστανται με πραγματικό κείμενο ή αποφεύγονται όπου είναι δυνατόν
I've applied the change. See https://github.com/w3c/wai-website/pull/841/commits/df533c0d156f047a535e7528b8fe0fffeff3a8c5

Please let me know if something is wrong.

2026-06-23 09:57 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Ο ήχος στο παρασκήνιο είναι χαμηλός ή μπορεί να απενεργοποιηθεί, για να αποφευχθούν παρεμβολές ή απόσπαση της προσοχής
@Xrisanthi-Mil I understand that no changes were finally made to this line. Please let me know if I missed a requested change. cc @avourliotakis

2026-06-23 09:58 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +Τα εναλλακτικά κείμενα είναι ισοδύναμα για το μη κειμενικό περιεχόμενο. Τα παραδείγματα περιλαμβάνουν.
I've applied the change. See https://github.com/w3c/wai-website/pull/841/commits/ce4d460606980159b83333712f581631fab8cf18

Please let me know if something is wrong.

2026-06-23 10:05 UTC, avourliotakis commented on pages/fundamentals/accessibility-principles/index.el.md
> +-   Σύντομα ισοδύναμα για εικόνες, συμπεριλαμβανομένων εικονιδίων, κουμπιών και γραφικών
No changes. Here's the final:

Τα εναλλακτικά κείμενα είναι ισοδύναμα για το μη κειμενικό περιεχόμενο. Τα παραδείγματα περιλαμβάνουν:

- Σύντομα ισοδύναμα για εικόνες, συμπεριλαμβανομένων εικονιδίων, κουμπιών και γραφικών

2026-06-23 10:05 UTC, remibetin commented on pages/fundamentals/accessibility-principles/index.el.md
> +- [[Elias, συνταξιούχος με περιορισμένη όραση, τρέμουλο στα χέρια και ήπιου βαθμού απώλεια βραχυπρόθεσμης μνήμης]](/people-use-web/user-stories/story-nine/)
Indeed, thanks for noticing! The latest version uses double brackets.

2026-06-29 09:24 UTC, merged