[Simplified Chinese] W3C Accessibility Standards Overview
w3c/wai-website pull request #953
Opened 2024-11-07 05:07 UTC by heybran

2024-11-20 01:15 UTC, JinMokai approved these changes
@remibetin  The translation looks okay.🎉

2024-11-25 11:40 UTC, remibetin requested changes
Thanks @heybran. I have noticed a few things:
- The "Personalization" section needs update. It is now named "WAI-Adapt" and its content has been updated in 2022 (see the [Changes history](https://www.w3.org/WAI/standards-guidelines/changelog/#30-june-2022))
- Image: we have recently changed the way we link to the long description of the image. Can you apply the new method? The new code is available at: (please translate the alt text)
https://github.com/w3c/wai-website/blob/669c8821b3475907c6c322ddd94d053281454cdc/pages/standards-guidelines/index.md?plain=1#L171-L172
- If you are interested in translating the image, please read [How to Translate Images
](https://www.w3.org/WAI/about/translating/resources/images/). Let me know if you prefer we publish the translation without the translated image for now.

2024-11-25 11:40 UTC, remibetin commented on pages/standards-guidelines/index.zh-hans.md
> +- [[无障碍一致性测试（ACT）概述]](/standards-guidelines/act/) &mdash; ACT 建立并记录规则，用来测试 Web 内容是否与可访问性标准一致。[WCAG 2 测试规则](/standards-guidelines/act/rules/about) 使用ACF规则格式。
```suggestion
- [[无障碍一致性测试（ACT）概述]](/standards-guidelines/act/) &mdash; ACT 建立并记录规则，用来测试 Web 内容是否与可访问性标准一致。[WCAG 2 测试规则](/standards-guidelines/act/rules/about) 使用ACT规则格式。
```

Typo?

2024-11-29 03:30 UTC, heybran commented
@remibetin Translations updated: https://deploy-preview-953--wai-website.netlify.app/standards-guidelines/zh-hans

Regarding:

> If you are interested in translating the image, please read [How to Translate Images](https://www.w3.org/WAI/about/translating/resources/images/). Let me know if you prefer we publish the translation without the translated image for now.

Please kindly publish the translation without the translated image for now if the updated translations are all good.

2024-12-12 17:10 UTC, remibetin commented
Thanks @heybran. I am checking a few things and should be able to get back to you next week.

2024-12-16 11:02 UTC, remibetin requested changes

2024-12-16 11:02 UTC, remibetin commented on pages/standards-guidelines/index.zh-hans.md
> +- [[无障碍一致性测试（ACT）概述]](/standards-guidelines/act/) &mdash; ACT 建立并记录规则，用来测试 Web 内容是否与可访问性标准一致。[WCAG 2 测试规则](/standards-guidelines/act/rules/about) 使用ACT规则格式。
```suggestion
- [[无障碍一致性测试（ACT）概述]](/standards-guidelines/act/) &mdash; ACT 建立并记录规则，用来测试 Web 内容是否与可访问性标准一致。[WCAG 2 测试规则](/standards-guidelines/act/rules/about/) 使用ACT规则格式。
```

2024-12-16 19:12 UTC, remibetin commented
Thanks @heybran. I have completed my review and added a few comments.

2024-12-18 03:52 UTC, heybran commented
@remibetin Updated.

2024-12-19 09:15 UTC, merged